### ISSUE TITLE
binary replication montitoring metrics

### ISSUE THREAD

**Issue by jinty** [wrouesnel/postgres_exporter#1]
Hi,

I'm interested in using your exporter to monitor a streaming replication cluster. However it looks like it's missing a few metrics, specifically these would be interesting:

```
pg_is_in_recovery()
pg_last_xact_replay_timestamp()
pg_last_xlog_replay_location()
pg_last_xlog_receive_location()
pg_current_xlog_location()
pg_is_in_backup()
```

from http://www.postgresql.org/docs/9.4/static/functions-admin.html

**Comment by jinty** [comment]
sorry for not attempting a pull request, but, er never done any go programming before and whatever I did would probably need a re-write...

**Comment by wrouesnel** [comment]
No problem - I am interested in supporting those in metrics. I'll have 
to examine our current postgres instance, since I believe our DBAs set 
up replication so I should have a good test case.

**Comment by wrouesnel** [comment]
We have pg_stat_replication now, but looking at this list again it's not actually what you were looking for. The new code to handle it extends the model quite well though, so we should be able to support this. Leaving this open after all.
