### ISSUE TITLE
not compact pg9.6.3

### ISSUE THREAD

**Issue by qianfangyuan** [wrouesnel/postgres_exporter#101]
env:
CentOS6
PG9.6.3

operation:

export DATA_SOURCE_NAME="postgresql://postgres:@localhost:5432/xx?sslmode=disable"
./postgres_exporter &
[root@localhost data]# INFO[0000] Established new database connection. source=postgres_exporter.go:951
INFO[0000] Semantic Version Changed: 0.0.0 -> 9.6.3 source=postgres_exporter.go:904
panic: Unknown unit for runtime variable: "16kB"

goroutine 7 [running]:
main.(*pgSetting).metric(0xc4200556d0, 0xc4200a3d98, 0x5)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/pg_setting.go:69 +0x4e0
main.querySettings(0xc42001a960, 0xc4200e5400, 0x0, 0x0)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/pg_setting.go:38 +0x422
main.(*Exporter).scrape(0xc4201100e0, 0xc42001a960)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:991 +0x4ef
main.(*Exporter).Collect(0xc4201100e0, 0xc42001a960)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:747 +0x39
main.(*Exporter).Describe(0xc4201100e0, 0xc42001a900)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:740 +0xb0
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x9459c0, 0xc4201100e0, 0xc42001a900)
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:220 +0xbc

[1]+ Exit 2 ./postgres_exporter

error with:panic: Unknown unit for runtime variable: "16kB"

**Comment by wrouesnel** [comment]
Definitely a bug. Let me dig into it.

**Comment by wrouesnel** [comment]
I've opened PR #102 which I believe should resolve this issue. I'll merge it once CI passes and push a release.

**Comment by zhoulhb** [comment]
env:
CentOS7.x
PG 10.7

operation:

export DATA_SOURCE_NAME="postgresql://postgres:@localhost:5432/xx?sslmode=disable"
./postgres_exporter &
[root@localhost data]# INFO[0000] Established new database connection. source=postgres_exporter.go:1335
INFO[0000] Semantic Version Changed: 0.0.0 -> 10.7.0 source=postgres_exporter.go:904
panic: Unknown unit for runtime variable: "64kB"

goroutine 7 [running]:
...

**Comment by zhoulhb** [comment]
hi guys, i guess this error is because of the postgres_exporter not compatible with centos, it only working on debian os.  i hope you can resolve this bug.
