### ISSUE TITLE
Make the DATA_SOURCE_URI environment variable a real URI

### ISSUE THREAD

**Issue by rgl** [wrouesnel/postgres_exporter#113]
The `DATA_SOURCE_URI` environment variable is not really an URI as seen in:

https://github.com/wrouesnel/postgres_exporter/blob/6e3d130f40423ef7a55bcc9f971fce79e40e4ff2/postgres_exporter.go#L1033-L1034

It's part of the URI. What do you think in making it really an uri? Like `postgresql://postgres@localhost:5432?sslmode=disable`, then later parse it to set the user and password if the corresponding environment variable exists (that would also prevent uri escaping issues that exist with the current code, as it simply concatenates the user and pass without proper escaping).

BTW, why was there a need to introduce a new environment variable? Why not reuse the `DATA_SOURCE_NAME`? This seems like a compatible change.

**Comment by wrouesnel** [comment]
I'm not sure what functional improvements this issue would bring? I'm hesitant to change configuration behavior like this at this point, since backwards compatibility does matter somewhat.

**Comment by rgl** [comment]
None. Its a matter of expectation, that is, when I have a variable with the `URI` word in its name I would assume its an URI/URL; but in this case its not really an URI. So its strange. Anyways, functionally, `DATA_SOURCE_NAME` works fine for me.

**Comment by larsks** [comment]
I came here for the same reason...`DATA_SOURCE_URI` isn't a URI. It's apparently just a hostname. If  don't want to change the code to accept an actual URI, and you want to keep the existing name for consistency, perhaps update the docs to make this clear?
