### ISSUE TITLE
Add hostname to labels for all metrics

### ISSUE THREAD

**Issue by pvdvreede** [wrouesnel/postgres_exporter#115]
It looks like at the moment there are labels for the dbname but I couldnt see a label for the db hostname.

We would like to run the exporter for different postgres servers against a single prometheus so would need to be able to filter by the hostname as part of the metric's label. Is this currently possible? Or easy to add?

Thanks.

**Comment by wrouesnel** [comment]
Normally you would run 1 exporter per server, and on the Prometheus side the instance-name's would be how you filter (or you could append labels at the Prometheus end).

It's been on my mind to let the exporter work a bit more like the blackbox_exporter and let prometheus drive it remotely, but that would still be very similar.

**Comment by bazmap** [comment]
Link to this one #451
