### ISSUE TITLE
Query row metrics always return 0

### ISSUE THREAD

**Issue by krishofmans** [wrouesnel/postgres_exporter#117]
Hi,

Problem description:
I've tried running `latest` and `v0.2.3` against the postgres database, but certain metrics never show up. For example: fetched, returned, inserted, updated and deleted.

This is while there is active load on the server to generate these numbers.

```monitoring-docker:~$ curl localhost:9187/metrics | grep tup_fetched
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60118  100 60118    0     0   1989      0  0:00:30  0:00:30 --:--:-- 15105
# HELP pg_stat_database_tup_fetched Number of rows fetched by queries in cu database
# TYPE pg_stat_database_tup_fetched counter
pg_stat_database_tup_fetched{datid="1",datname="template1"} 0
pg_stat_database_tup_fetched{datid="13052",datname="template0"} 0
pg_stat_database_tup_fetched{datid="13057",datname="postgres"} 0
pg_stat_database_tup_fetched{datid="16857",datname="demodata"} 0
pg_stat_database_tup_fetched{datid="16858",datname="metadata"} 0
```

Other metrics like the cache hit ratio also seem empty, there might be a correlation. 

Container output:
```monitoring-docker:~$ docker run --rm -e DATA_SOURCE_NAME="postgresql://postgres:password@ip:5432/?sslmode=disable" -p 9187:9187 wrouesnel/postgres_exporter:latest
time="2017-10-16T14:46:25Z" level=info msg="Established new database connection." source="postgres_exporter.go:952"
time="2017-10-16T14:46:25Z" level=info msg="Semantic Version Changed: 0.0.0 -> 9.4.14" source="postgres_exporter.go:905"
time="2017-10-16T14:46:55Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1075"
```

Please feel free to ask me any additional information.
Kris

**Comment by wrouesnel** [comment]
Could you run with -log.level=debug and post the output.

**Comment by krishofmans** [comment]
Hi @wrouesnel 

Thanks for your reply, here's the output after one curl call:

`docker run --rm -e DATA_SOURCE_NAME="postgresql://xxxxxxxxxx/postgres?sslmode=disable" -p 9187:9187 wrouesnel/postgres_exporter:latest -log.level=debug
time="2017-10-17T15:15:08Z" level=info msg="Established new database connection." source="postgres_exporter.go:952"
time="2017-10-17T15:15:08Z" level=debug msg="Querying Postgres Version" source="postgres_exporter.go:888"
time="2017-10-17T15:15:08Z" level=info msg="Semantic Version Changed: 0.0.0 -> 9.4.14" source="postgres_exporter.go:905"
time="2017-10-17T15:15:08Z" level=debug msg="procpid is being forced to discard due to version incompatibility." source="postgres_exporter.go:497"
time="2017-10-17T15:15:08Z" level=debug msg="Querying pg_setting view" source="pg_setting.go:17"
time="2017-10-17T15:15:08Z" level=debug msg="Querying namespace:  pg_stat_database" source="postgres_exporter.go:868"
time="2017-10-17T15:15:18Z" level=debug msg="Querying namespace:  pg_stat_database_conflicts" source="postgres_exporter.go:868"
time="2017-10-17T15:15:28Z" level=debug msg="Querying namespace:  pg_locks" source="postgres_exporter.go:868"
time="2017-10-17T15:15:28Z" level=debug msg="Querying namespace:  pg_stat_replication" source="postgres_exporter.go:868"
time="2017-10-17T15:15:28Z" level=debug msg="Querying namespace:  pg_stat_activity" source="postgres_exporter.go:868"
time="2017-10-17T15:15:28Z" level=debug msg="Querying namespace:  pg_stat_bgwriter" source="postgres_exporter.go:868"
time="2017-10-17T15:15:38Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1075"
time="2017-10-17T15:16:11Z" level=debug msg="Querying Postgres Version" source="postgres_exporter.go:888"
time="2017-10-17T15:16:11Z" level=debug msg="Querying pg_setting view" source="pg_setting.go:17"
time="2017-10-17T15:16:11Z" level=debug msg="Querying namespace:  pg_stat_bgwriter" source="postgres_exporter.go:868"
time="2017-10-17T15:16:21Z" level=debug msg="Querying namespace:  pg_stat_database" source="postgres_exporter.go:868"
time="2017-10-17T15:16:31Z" level=debug msg="Querying namespace:  pg_stat_database_conflicts" source="postgres_exporter.go:868"
time="2017-10-17T15:16:41Z" level=debug msg="Querying namespace:  pg_locks" source="postgres_exporter.go:868"
time="2017-10-17T15:16:41Z" level=debug msg="Querying namespace:  pg_stat_replication" source="postgres_exporter.go:868"
time="2017-10-17T15:16:41Z" level=debug msg="Querying namespace:  pg_stat_activity" source="postgres_exporter.go:868"`

The output from curl looks like this:
`monitoring-docker:~$ curl localhost:9187/metrics | grep tup_fetched
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0# HELP pg_stat_database_tup_fetched Number of rows fetched by queries in cu database
# TYPE pg_stat_database_tup_fetched counter
pg_stat_database_tup_fetched{datid="1",datname="template1"} 0
pg_stat_database_tup_fetched{datid="13052",datname="template0"} 0
pg_stat_database_tup_fetched{datid="13057",datname="postgres"} 0
pg_stat_database_tup_fetched{datid="16857",datname="i2b2demodata"} 0
pg_stat_database_tup_fetched{datid="16858",datname="i2b2metadata"} 0
100 59886  100 59886    0     0   1980      0  0:00:30  0:00:30 --:--:-- 14904`

One thing to note is that it always seems to cut off after *exactly* 30 seconds. I've been told this is a 750GB postgres db, perhaps postgres is taking too long to gather the statistics?

Thanks,
Kris

**Comment by wrouesnel** [comment]
Ah interesting. We're definitely tripping some type of timeout - curious that the metric still emits though.

Are you using a queries.yaml file at all? If so try disabling that. Looks like I need to investigate what happens when query timeouts trigger because it should throw an error.

**Comment by krishofmans** [comment]
Nope, no custom queries whatsoever, just the vanilla docker container, docker run command just like in the readme. 

I will run the queries directly from a postgres client to see if they timeout and return 0's, or if they emit some sort of other error message to determine if it's postgres behaviour to do that, potentially they have a setting for the timeout, or if it's somewhere in the go code.

Let me know if tou want my to try anything else.

Thanks,
Kris

**Comment by krishofmans** [comment]
Okay, so I ran some tests using a postgres client directly:

`SELECT * from pg_catalog.pg_stat_database;` executes in 10s 75ms, so I find this a bid odd as well, since it's always 10 second-ish. I feel like I'm running into some internal postgres timeout.

The results that I get already all have 0's.

![image](https://user-images.githubusercontent.com/999774/31773450-1906d26e-b4e3-11e7-9e7c-5260b0f38ed9.png)

This leads me to believe that I need a postgres expert :)

**Comment by wrouesnel** [comment]
Have you perhaps disabled the statistics modules? I haven't seen behaviour like this - you probably need to turn the logging level on your server up and see if you get a timeout notice.

**Comment by krishofmans** [comment]
@wrouesnel i've added 2 other postgresses in the infrastructure here, and one of them works as expected:
![image](https://user-images.githubusercontent.com/999774/31986679-ae3e7528-b969-11e7-8af2-0779d7e465ef.png)

So clearly it's an issue over here, I'm closing this ticket, your exporter works fine, it won't be something fixable in your code.

Thank you for the support, if I receive feedback from the config changes required, I will add the information here for future reference.
