### ISSUE TITLE
Postgres 10.0 Error

### ISSUE THREAD

**Issue by Zolmeister** [wrouesnel/postgres_exporter#119]
```
Error running query on database:  pg_stat_replication pq: function pg_current_xlog_location() does not exist\n" source="postgres_exporter.go:873
```

Presumably caused by the rename of `pg_xlog` to `pg_wal`

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=f82ec32ac30ae7e3ec7c84067192535b2ff8ec0e

**Comment by keithf4** [comment]
Could there either be an option to disable the built in queries or just consider removing them all together and go entirely with an external file to supply the queries to run? When the internal ones break like this due to catalog changes, it causes issues that are hard to then fix without hacking on the go source code and recompiling.

**Comment by wrouesnel** [comment]
That's a good idea actually. PG 10s release has coincided unfortunately worth a busy time for me so I've not been on the ball with updating for it.

I need to get to it soon.

On 23 October 2017 2:30:41 pm AEDT, Keith Fiske <notifications@github.com> wrote:
>Could there either be an option to disable the built in queries or just
>consider removing them all together and go entirely with an external
>file to supply the queries to run? When the internal ones break like
>this due to catalog changes, it causes issues that are hard to then fix
>without hacking on the go source code and recompiling.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wrouesnel/postgres_exporter/issues/119#issuecomment-338539046

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by keithf4** [comment]
Removing the built in queries would certainly cut down on the required maintenance of the core code. Allowing multiple query files to be defined would be nice as well. I tried defining `-extend.query-path` more than once, but it only uses the last one defined. Would allow a core set of queries to use the same file everywhere and add additional ones as needed on certain systems.
