### ISSUE TITLE
Version 0.3.0 Can't Connect to Database

### ISSUE THREAD

**Issue by jcantu-usgs** [wrouesnel/postgres_exporter#120]
I have the postgres_exporter setup as an init.d service.  In the /etc/sysconfig/postgres_exporter configuration file I have the database connection setup like so:
DATA_SOURCE_NAME=postgresql://postgres:postgres@localhost:5432?sslmode=disable

In the /var/log/prometheus/postgres_exporter.log, I am seeing the following message:

`time="2017-10-24T00:30:05Z" level=info msg="Error opening connection to database (postgresql://:PASSWORD_REMOVED@): pq: SSL is not enabled on the server" source="postgres_exporter.go:996" 
time="2017-10-24T00:30:05Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1093" `

It never actually seems to connect.  I can hit the url and see that it's running but there are no useful metrics and it seems like there is a scraping error:

\# TYPE pg_exporter_last_scrape_error gauge
pg_exporter_last_scrape_error 1
\# HELP pg_exporter_scrapes_total Total number of times PostgresSQL was scraped for metrics.
\# TYPE pg_exporter_scrapes_total counter
pg_exporter_scrapes_total 2

**Comment by wrouesnel** [comment]
Set --log.level=debug and see if that provides more information.

But that looks weird since the tests don't run with SSL normally.

**Comment by jcantu-usgs** [comment]
As you can see below, everything looks good (running with --log.level=debug) but there is no further information in the log.  I can login to the postgres server using the same user and password in the DATA_SOURCE_NAME string.

`[vagrant@localhost ~]$ sudo cat /etc/sysconfig/postgres_exporter
DATA_SOURCE_NAME=postgresql://postgres:postgres123@localhost:5432/postgres
[vagrant@localhost ~]$ sudo service postgres_exporter status
postgres_exporter (pid  5797) is running...
[vagrant@localhost ~]$ sudo ps -ef | grep postgres_exporter
497       5797     1  0 18:23 ?        00:00:00 /usr/bin/postgres_exporter --log.level=debug
vagrant   5823  5165  0 18:24 pts/0    00:00:00 grep postgres_exporter
[vagrant@localhost ~]$ sudo cat /var/log/prometheus/postgres_exporter.log 
time="2017-10-24T18:23:40Z" level=info msg="Error opening connection to database (postgresql://:PASSWORD_REMOVED@): pq: SSL is not enabled on the server" source="postgres_exporter.go:996" 
time="2017-10-24T18:23:40Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1093" 
[vagrant@localhost ~]$ psql --user=postgres -W
Password for user postgres: 
psql (10.0)
Type "help" for help.

postgres=# \q
[vagrant@localhost ~]$ sudo lsof -i :5432
COMMAND    PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
postmaste 5669   postgres    3u  IPv6  76097      0t0  TCP localhost:postgres (LISTEN)
postmaste 5669   postgres    4u  IPv4  76098      0t0  TCP localhost:postgres (LISTEN)
postgres_ 5797 prometheus    6u  IPv6  77438      0t0  TCP localhost:45636->localhost:postgres (CLOSE_WAIT)
`

**Comment by jcantu-usgs** [comment]
For the record, I've tried setting DATA_SOURCE_NAME in the environment and running the postgres_exporter directly.  The result is exactly the same.

**Comment by jcantu-usgs** [comment]
I got it working by adding 'export' out in front of the DATA_SOURCE_NAME environment variable in the sysconfig.  I guess I didn't realize that would be required because all of the examples I saw for sysconfig didn't use that qualifier.
