### ISSUE TITLE
Master version does not work

### ISSUE THREAD

**Issue by fragtom** [wrouesnel/postgres_exporter#124]
Current version master does not start as expected.. v0.30 works

```
tom.stark@MBproTStark prometheus-monitoring (aws)  $ kubectl --context=aws -n monitoring logs -f postgres-exporter-3136023989-shqws 
postgres_exporter: error: unknown short flag '-e', try --help
````

**Comment by wrouesnel** [comment]
Upstream Prometheus has moved to kingpin cli parsing so the next release is going to follow. The main difference is flags now need double hyphens.

**Comment by wrouesnel** [comment]
Closing this issue unless there's further developments.
