### ISSUE TITLE
Dumb question: how to build this package?

### ISSUE THREAD

**Issue by CrystalSu** [wrouesnel/postgres_exporter#126]
I downloaded the zip file and unzipped to my local Mac machine.
In a Terminal, I cd to the unzipped the folder and did a "make", then it hangs at:
```
crystals-mbp:postgres_exporter crystalsu$ make
...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C tools
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
make[1]: Nothing to be done for `DEFAULT'.
gometalinter --disable-all --enable=gofmt --vendor
cat: /proc/cpuinfo: No such file or directory
cat: /proc/cpuinfo: No such file or directory
Using 0 processes
gometalinter -j        0 --deadline=30s --disable=gotype --disable=gocyclo 
```

**Comment by wrouesnel** [comment]
Unfortunately the Makefile is Linux only for the time being. But if you have a functional golang environment then extracting to `$GOPATH/src/github.com/wrouesnel/postgres_exporter` and running `go build github.com/wrouesnel/postgres_exporter` should get it done.

**Comment by wrouesnel** [comment]
As an update as of 0.4.1 the new packaging format means Darwin (Mac) binaries are now available.
