### ISSUE TITLE
Can not connect to DB

### ISSUE THREAD

**Issue by wdp-007** [wrouesnel/postgres_exporter#129]
Hi,

I tried Quick start on my mac by running below command:
docker run --net=host -it --rm -e POSTGRES_PASSWORD=password postgres
docker run -e DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/?sslmode=disable" -p 9187:9187 wrouesnel/postgres_exporter
But I got error as:
Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@localhost:5432/?sslmode=disable): dial tcp 127.0.0.1:5432: getsockopt: connection refused" source="postgres_exporter.go:984

I changed localhost to my host IP, still get this error.

Then I try to start exporter with docker-compose:
  postgresexporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    restart: always
    expose:
      - 9113
    ports:
      - 9113:9113
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:password@localhost:5432/?sslmode=disable

Still get same error.....

Can anyone give me some advise?Thanks!

**Comment by wrouesnel** [comment]
Docker for Mac runs in a VM. Depending where you're running postgres, you need to provide the IP to either the VM, your Mac (as seen from the docker host IP) or another container on the container network.

Best to confirm what your container can see by using the postgres container in docker to run the psql client and checking you can connect to the database server that way.

**Comment by amit-handa** [comment]
Hi, I am running docker container on 17.10 ubuntu and getting same error.
psql -U <user> -h 127.0.0.1 -p 5432
<password>
... connects ...

But the docker container says connection refused.
I tried getting interactive shell (bash) to debug. but its absent. ls etc arent available as well.
please help. I am new to docker. I have instalIed docker fresh (docker-ce)
