### ISSUE TITLE
Question: How to only get specified entries in metrics

### ISSUE THREAD

**Issue by CrystalSu** [wrouesnel/postgres_exporter#131]
By default, many many entries are exported to the host/metrics end point.
What if I'm only interested in a very small subset of them, how can I make the exporter not to put the rest at host/metrics end point?

For example, if I'm only interested on pg_stat_activity_count for a specific database in a specific Prometheus job, with Prometheus I can do
```
http://monitor.ip.address:9090/api/v1/series?match[]={__name__=%27pg_stat_activity_count%27,job=%27postgres%27,datname=%27postgres%27}
```
to only see what I want.

However, I would prefer only this small subset of data ever got to `postgres.server.ip:5432/metrics`.
How can I do this? Do you have an example?
Thanks.

**Comment by wrouesnel** [comment]
As a rule I don't really want the exporter to be in the metric filtering business. Prometheus should be able to rewrite or drop metrics on the ingest side if they're undesired, but the total datasize in transit is always going to be "small".
