### ISSUE TITLE
Proxy "up" metric

### ISSUE THREAD

**Issue by SuperQ** [wrouesnel/postgres_exporter#135]
It would be good to have a proxy "up" metric for when the exporter is up, but the pg server can't be reached.

It's slightly different than `pg_exporter_last_scrape_error`, as the symantics are more like `up`, but also it can be used to differentiate between a connected a server, and other scrape errors, or a problem with a single collector.

**Comment by keithf4** [comment]
We currently use a shell script with pg_isready and node_exporter for this. Something built into postgres_exporter would be great too.

**Comment by wrouesnel** [comment]
This should be pretty straight forward to do - we just need to look for the connection error.

**Comment by SuperQ** [comment]
@wrouesnel Thanks, but it really should be `pg_up` to follow the normal proxy up convention.

**Comment by wrouesnel** [comment]
I wasn't aware (and hence the reason we have an RC and not a release). I'll fix it.
