### ISSUE TITLE
Version check doesn't handle EnterpriseDB version strings

### ISSUE THREAD

**Issue by huiser** [wrouesnel/postgres_exporter#142]
Log:
`level=warning msg="Proceeding with outdated query maps, as the Postgres version could not be determined: Error parsing version string: Could not find a postgres version in string: EnterpriseDB 9.6.5.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit\n" source="postgres_exporter.go:1019"`

Version check regexp should accept an optional fourth part.

**Comment by huiser** [comment]
This works for me:
`--- a/postgres_exporter.go
+++ b/postgres_exporter.go
@@ -80,7 +80,7 @@ func (cu *ColumnUsage) UnmarshalYAML(unmarshal func(interface{}) error) error {
 }
 
 // Regex used to get the "short-version" from the postgres version field.
-var versionRegex = regexp.MustCompile(`^\w+ ((\d+)(\.\d+)?(\.\d+)?)\s`)
+var versionRegex = regexp.MustCompile(`^\w+ ((\d+)(\.\d+)?(\.\d+)?)(\.\d+)?\s`)
 var lowestSupportedVersion = semver.MustParse("9.1.0")
 
 // Parses the version of postgres into the short version string we can use to
`

**Comment by marcinbudny** [comment]
There is a similar problem with Postgres on Windows:
`msg="Proceeding with outdated query maps, as the Postgres version could not be determined: Error parsing version string: Could not find a postgres version in string: PostgreSQL 9.5.4, compiled by Visual C++ build 1800, 64-bit\n"`
