### ISSUE TITLE
Postgres 10 incompatibility.

### ISSUE THREAD

**Issue by jzampieron** [wrouesnel/postgres_exporter#143]
We are getting many : 
```
postgres|postgres|HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres|postgres|LOCATION:  ParseFuncOrColumn, parse_func.c:528
postgres|postgres|STATEMENT:  
                SELECT *,
                    pg_current_xlog_location()
                FROM pg_stat_replication
```

Entires in the logs. It appears that `pg_current_xlog_location` was replaced by `pg_current_wal_lsn`.

**Comment by keithf4** [comment]
Just wondering if you have an ETA for 10 support? We have a client asking for any concerns with upgrading postgres and so far our only concern is that they won't be able to monitor it without tons of scrape errors. :)  Making another request to just remove the built in queries to avoid blocks like this in the future when system catalogs change again.

**Comment by wrouesnel** [comment]
10 is supported now (it's included in the testing plan). I thought I had fixed this - I'll take a look.

**Comment by wrouesnel** [comment]
Just looked now - there are explicit discards for handling this case for pg_stat_replication and 10. Check you're using the latest version.

**Comment by jzampieron** [comment]
Upon updating to v0.4.1. this error is gone.
