### ISSUE TITLE
Failed to get host and db in templating

### ISSUE THREAD

**Issue by Allen-yan** [wrouesnel/postgres_exporter#148]
I 'm using the Grafana v4.6.3, and copy the dashboard from https://grafana.com/dashboards/3300.
![image](https://user-images.githubusercontent.com/5153861/35145899-666ff1f8-fd44-11e7-8734-e05f2fcee5aa.png)

The pg is using for the gitlab . I have found data in prometheus web query 

Any help ?

**Comment by saifulmuhajir** [comment]
Did you check your data source in Grafana for templating?

Check the metric output from http://<YOUR_HOST>:9187/metrics and see if it shows metrics. If it does, you need to verify again on Prometheus configuration file. If you already did, verify again your data source on Grafana.

**Comment by wrouesnel** [comment]
Didn't see any more activity on this so closing.

**Comment by dortonway** [comment]
I have the same problem. Metrics are exposed, Prometheus gets them (I see it on the targets page), I added two dashboards:
https://grafana.com/dashboards/455
https://grafana.com/dashboards/3742

The first one somehow knows the url of the server with postgres_exporter - it's possible to select at the top. But there are no metrics in both Dashboards.

How to fix that?

**Comment by dortonway** [comment]
@saifulmuhajir

**Comment by saifulmuhajir** [comment]
You might need to adjust the parameters in the panels itself. Check your metrics and see the metrics name and so on, and adjust the panels accordingly.
