### ISSUE TITLE
cannot parse some SHOW variables

### ISSUE THREAD

**Issue by jinty** [wrouesnel/postgres_exporter#15]
I was trying out the latest master and get this:

```
time="2016-07-27T14:07:50Z" level=error msg="Unexpected error parsing column:  pg max_pred_locks_per_transaction 64" file="postgres_exporter.go" line=471
time="2016-07-27T14:07:50Z" level=error msg="Unexpected error parsing column:  pg max_identifier_length 63" file="postgres_exporter.go" line=471
time="2016-07-27T14:07:50Z" level=error msg="Unexpected error parsing column:  pg max_locks_per_transaction 64" file="postgres_exporter.go" line=471
```

This is querying postgresql 9.5. It seems that the query:

SHOW max_pred_locks_per_transaction;

returns a "text" type. But eyeballing the code, that should work...

**Comment by wrouesnel** [comment]
Interesting, AFAIK all of those types of queries should be working fine on 9.5 (there are harmless errors only when stepping back in versions).
