### ISSUE TITLE
'make' build failure

### ISSUE THREAD

**Issue by SamwiseGambgee** [wrouesnel/postgres_exporter#159]
Hello everyone,
I'm facing problems in natively building the go file without the docker.
I getting the below error:
`make -C tools`
`make[1]: Entering directory '/home/work/src/github.com/wrouesnel/postgres_exporter/tools'`
`metatools.deps:35: warning: overriding recipe for target 'bin/gotype'`
`metatools.deps:23: warning: ignoring old recipe for target 'bin/gotype'`
`GOPATH=/home/work/src/github.com/wrouesnel/postgres_exporter/tools go install -v`
`mvdan.cc/unparam`
`mvdan.cc/unparam/check`
`# mvdan.cc/unparam/check`
`src/mvdan.cc/unparam/check/check.go:131: undefined: types.SizesFor`
`src/mvdan.cc/unparam/check/check.go:347: undefined: sort.Slice`
`metatools.deps:33: recipe for target 'bin/unparam' failed`
`make[1]: *** [bin/unparam] Error 2`
`make[1]: Leaving directory '/home/work/src/github.com/wrouesnel/postgres_exporter/tools'`
`Makefile:115: recipe for target 'tools' failed`
`make: *** [tools] Error 2`

Can anyone please help me thru it?

Thanks!

**Comment by SamwiseGambgee** [comment]
Do I have to update my Golang?
my current version is: `go1.6.2`

**Comment by wrouesnel** [comment]
Yes definitely - travis builds at 1.9 at the moment.

**Comment by wrouesnel** [comment]
You should be able to build now using the new build system which is triggered via `go run mage.go` and doesn't depend on make at all. Go version will still be important.

Closing this issue unless there's further problems.

**Comment by SamwiseGambgee** [comment]
Thank you @wrouesnel. Sorry I forgot to mark this issue as 'Completed' in the comments.
