### ISSUE TITLE
pg_up accuracy issues

### ISSUE THREAD

**Issue by Tom-Fawcett** [wrouesnel/postgres_exporter#160]
_postgres_exporter v0.4.1_ 

I experienced an incident on a Postgres database, which was picked up by a blackbox_exporter TCP probe.

The probe failed between 11:43:47-11:55:47 (approx).

During that time period pg_up remained equal to 1, apart from a few minutes of being absent.

pg_exporter_last_scrape_error was reasonably accurate in tracking the incident. 

The postgres_exporter logs mainly contained "connection refused" for the duration of the incident.

Could the accuracy of pg_up be improved, so that I longer need to rely on the blackbox_exporter probe?

----
#### pg_up graph
![pg_up](https://user-images.githubusercontent.com/11577089/36907243-0d996494-1e30-11e8-9c92-1b6ee1628f1f.png)

#### pg_exporter_last_scrape_error graph
![pg_exporter_last_scrape_error](https://user-images.githubusercontent.com/11577089/36907244-0db045e2-1e30-11e8-8a43-9e5bbd2ebc6f.png)

[postgres_exporter_redacted.log](https://github.com/wrouesnel/postgres_exporter/files/1775715/postgres_exporter_redacted.log)

**Comment by karora** [comment]
I shut my database off for 30 minutes to test my alerting, and pg_up never blinked at all!

![screenshot from 2018-03-04 23-35-25](https://user-images.githubusercontent.com/147257/36952243-07acc87e-2005-11e8-81f6-21f4c4d4d637.png)

In the meantime I am using `1 - pg_exporter_last_scrape_error` but this seems a fairly severe issue.

**Comment by wrouesnel** [comment]
So originally I excluded a pg_up metric for exactly this reason - its meaning is ambiguous. The exporter can lose connection to postgres without actually determining if postgres is "up" which actually checks if its processing queries.

There's not really a good way to represent an indeterminate state like that - I.e. should we emit NaN to Prometheus when we just don't know, or - probably as I'll do - force pg_up to 0 if we get a connection error before we can send it.

**Comment by karora** [comment]
I think it is far better to show a false negative than a false positive in this case.  If pg_exporter is having trouble connecting then something, somewhere is wrong, and the issue merits investigation.

I'd also be OK if it simply didn't report the metric when it couldn't connect.  We can see that pg_exporter is still running with it's own metric, so I can act on "null or 0" and that could be useful information if it were documented.

The situation where I can connect to PostgreSQL but can't run queries is one I've never encountered.  Is it a common case?

**Comment by wrouesnel** [comment]
Looked at this today, looks like it really is just an oversight (the connect failed trips error, doesn't trip pgUp properly). Fixed and pushing a new release.

**Comment by Tom-Fawcett** [comment]
Thank you for the fast fix

**Comment by Tom-Fawcett** [comment]
@wrouesnel following #162 can pg_up ever be 1 now?

**Comment by wrouesnel** [comment]
Hmm I think you're right there, woops. I'll kill release 0.4.3 and fix that in 0.4.4, as well as add a test for it. 

Don't patch when the cat wakes you up early I guess :)

**Comment by Tom-Fawcett** [comment]
thanks @wrouesnel
