### ISSUE TITLE
Unable to build postgres_exporter

### ISSUE THREAD

**Issue by kkoppel** [wrouesnel/postgres_exporter#166]
Hi,

I'm trying to build postgres_exporter inside a golang Docker container, but I get an error when I try to "go get" the latest source code:
```
$ sudo docker run --rm --name=test -it --entrypoint=/bin/sh golang:alpine
/go # apk update
/go # apk add --no-cache git
/go # go get github.com/wrouesnel/postgres_exporter
package github.com/wrouesnel/postgres_exporter: build constraints exclude all Go files in /go/src/github.com/wrouesnel/postgres_exporter
/go # echo $?
1
/go # go version
go version go1.9.2 linux/amd64
```

If I ignore the error above and try to follow the build process given in the docs, then I get this:
```
/go # cd src/github.com/wrouesnel/postgres_exporter/
/go/src/github.com/wrouesnel/postgres_exporter # go run mage.go
2018/03/12 14:15:35 exec: git describe --dirty
2018/03/12 14:15:35 exec: git describe --abbrev=0
2018/03/12 14:15:35 exec: go list ./...
Targets:
  all                      runs a full suite suitable for CI
  assets                   builds binary assets to be bundled into the binary.
  autogen                  configure local git repository with commit hooks
  binary                   build a binary for the current platform
  clean                    deletes build output and cleans up the working directory
  coverage                 sums up the coverage profiles in .coverage.
  debug                    prints the value of internal state variables
  docker                   builds the docker image
  fmt                      automatically formats all source code files
  integrationTestBinary    Build the intgration test binary
  lint                     runs gometalinter for code quality.
  release                  builds release archives under the release/ directory
  releaseBin               builds cross-platform release binaries under the bin/ directory
  style                    checks formatting of the file.
  test                     run test suite
  testIntegration          runs integration tests
  tools                    builds build tools of the project and is depended on by all other build targets.
  updateTools              automatically updates tool dependencies to the latest version.
```

Am I doing something wrong?

BTW, with postgres_exporter up to v0.4.1 I would run "go get -u github.com/wrouesnel/postgres_exporter" inside the golang container and this would work just fine.

**Comment by syeda-saher73** [comment]
Hi,

I'm trying to build potgres_exporter
Getting the same error as above.

If I try to do go run mage.go all, I get this: 

go run mage.go all
2018/03/18 20:53:12 exec: git describe --dirty
2018/03/18 20:53:12 exec: git describe --abbrev=0
2018/03/18 20:53:12 exec: go list ./...
Finished 1 of 6
Finished 2 of 6
Finished 3 of 6
Finished 4 of 6
Finished 5 of 6
Finished 6 of 6
Error: failed to run "gometalinter --disable-all --enable=gofmt --enable=goimports /root/projects/src/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting_test.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter_integration_test.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter_test.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/mage.go /root/projects/src/src/github.com/wrouesnel/postgres_exporter/magefile.go: exec: "gometalinter": executable file not found in $PATH"
exit status 1

**Comment by syeda-saher73** [comment]
I tried this solution it worked:

go run mage.go binary
2018/03/18 22:37:17 exec: git describe --dirty
2018/03/18 22:37:17 exec: git describe --abbrev=0
2018/03/18 22:37:17 exec: go list ./...
github.com/alecthomas/gometalinter
Finished 1 of 6
Finished 2 of 6
Finished 3 of 6
Finished 4 of 6
Finished 5 of 6
Finished 6 of 6
Error: failed to run "go-bindata -pkg=assets -o assets/bindata.go -ignore=bindata.go -ignore=.*.map$ -prefix=assets/generated assets/generated/...: exec: "go-bindata": executable file not found in $PATH"
exit status 1


please install go-bindata:
go get -u -v github.com/jteeuwen/go-bindata
then go to $GOPATH. do this:
go install github.com/jteeuwen/go-bindata
go build
include go-bindata path in $PATH:
export PATH=$PATH:$GOPATH:src/github.com/jteeuwen/go-bindata/go-bindata

Now run:
go run mage.go binary

**Comment by kkoppel** [comment]
Thanks @syeda-saher73! While this helps to get the binary built after the code has been downloaded, even if I use the -d flag for "go get", I still get the same error about build constraints:
```
$ sudo docker run --rm --name=test -it --entrypoint=/bin/sh golang:alpine
/go # go get -d github.com/wrouesnel/postgres_exporter
package github.com/wrouesnel/postgres_exporter: build constraints exclude all Go files in /go/src/github.com/wrouesnel/postgres_exporter 
/go # echo $?
1
```

And that means the Docker image build process stops, which is a problem. I could of course use something like this to avoid the non-zero exit code:
```
go get -d github.com/wrouesnel/postgres_exporter || true
```
But that would ignore all errors and is obviously bad for automation. I have so far been unable to figure out how to avoid this error. Perhaps the build constraints should be changed somehow?

**Comment by wrouesnel** [comment]
The build system is currently a bit broken for tool builds due to vendoring and I haven't had the time to fix it yet (probably a conversion to dep is in order too).

@kkoppel what you're experiencing is the result of the real binary being built under `github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter`, which is the go-gettable path.

**Comment by wrouesnel** [comment]
@syeda-saher73 I'm aware of the issues with the build - it's due to vendoring working weird the way I'm trying to use it (too much manual tweaking). It's due for another pass.

**Comment by kkoppel** [comment]
Thanks @wrouesnel, changing the path solves my specific problem so I will close this issue.

**Comment by teoincontatto** [comment]
Please fix this in documentation also.

**Comment by jubel-han** [comment]
@kkoppel I'm facing the same issue, would you explain more about `changing the path`?

**Comment by kkoppel** [comment]
@jubel-han Previously I was doing this:
```
go get github.com/wrouesnel/postgres_exporter
```
but then I switched to this path instead:
```
go get github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter
```

**Comment by jubel-han** [comment]
@kkoppel It worked, thank you!

**Comment by bblaine** [comment]
> @jubel-han Previously I was doing this:
> 
> ```
> go get github.com/wrouesnel/postgres_exporter
> ```
> 
> but then I switched to this path instead:
> 
> ```
> go get github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter
> ```

Should the instructions in the "Building and Running"  in the README be updated to reflect this?

**Comment by comboy** [comment]
It would be great to add required go version in README. I also got this error and was clueless since I'm not familiar with go. Upgrading go to the latest version solved it for me.
