### ISSUE TITLE
--version reporting 0.0.1 on v0.4.4

### ISSUE THREAD

**Issue by keithf4** [wrouesnel/postgres_exporter#170]
I downloaded the binary for v0.4.4 on linux 64-bit (https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.4/postgres_exporter_v0.4.4_linux-amd64.tar.gz) to test out and when I ran --version to make sure i had the correct binary in my path, it returned this
```
$ postgres_exporter --version
postgres_exporter 0.0.1 (built with go1.10)
```
Previous version I had returned this
```
$ /usr/bin/postgres_exporter.old --version
postgres_exporter v0.4.1 (built with go1.8.3)
```

**Comment by wrouesnel** [comment]
Ooh, that's no good. I'll have a look.
