### ISSUE TITLE
Fail to start up the postgres_exporter by wal-segsize=64

### ISSUE THREAD

**Issue by Seiferbb** [wrouesnel/postgres_exporter#173]
Hi,I found that if I have change the wal-segsize in 32MB or 64MB  during compile source code， the postgres_exporter will start up fail by `Unknown unit for runtime variable:"32MB"`.
I found the reason that the unit does not supported by '32MB' or '64MB' from the query 
`SELECT name, setting, COALESCE(unit, ''), short_desc, vartype,* FROM pg_settings WHERE vartype IN ('bool', 'integer', 'real')`.

**Comment by wrouesnel** [comment]
@Seiferbb what version of postgres are you running? Should be an easy fix but I'm curious how it was missed in the first place...

**Comment by Seiferbb** [comment]
@wrouesnel I use postgres  version 9.5.3 .

**Comment by Seiferbb** [comment]
@wrouesnel I use postgres version 9.5.3 .And I found another file should be fix .
