### ISSUE TITLE
How is possible to reload/reconnect the postgres_exporter?

### ISSUE THREAD

**Issue by jose-l-goncalves** [wrouesnel/postgres_exporter#174]
Hi,

Is it possible send the SIGHUP (or other signal) to postgres_exporter's process to reload/reconnect all the connections?
I have tried, _kill -s 1 nn_. The process disconnect from postgres database and died. This is not the expected behaviour...

Thanks,
José Miguel Gonçalves

**Comment by wrouesnel** [comment]
No this is currently not supported.
