### ISSUE TITLE
how can i start postres_exporter in liux

### ISSUE THREAD

**Issue by gaozhenmin** [wrouesnel/postgres_exporter#176]

**Comment by wrouesnel** [comment]
The linux build here: https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.5/postgres_exporter_v0.4.5_linux-amd64.tar.gz will execute on any linux kernel with no dependencies. Run it with the configuration as shown on the README.md file of this repo.

You might also want to try the docker image.
