### ISSUE TITLE
Postgres Exporter logging the entire DATA_SOURCE_NAME which contains password

### ISSUE THREAD

**Issue by prateeknayak** [wrouesnel/postgres_exporter#181]
Thanks for creating the postgres exporter. Just found a tiny issue which might be relevant for protecting sensitive information.

```
Error opening connection to database (could not parse DATA_SOURCE_NAME): parse postgresql://master:<password>@<db_url>:%!s(int64=5432)/?sslmode=require: invalid URL escape \"%!s\"" source="postgres_exporter.go:1012
```

**Comment by wrouesnel** [comment]
Urgh...password fields have been a constant problem like this. Originally we just didn't log them for this reason. Noted.

**Comment by devlounge** [comment]
Any chance this gets fixed soon?

**Comment by wrouesnel** [comment]
It should be fixed now.
