### ISSUE TITLE
Postgres Exporter converts time into epoch timestamp

### ISSUE THREAD

**Issue by jreineke-nli** [wrouesnel/postgres_exporter#182]
Hi,

thanks for the great exporter.
Recently i came across a strange behaviour of the postgres exporter. I am trying to put a time value e.g. "2018-04-10 14:12:03.714" from a sql statement within my custom query file in a prometheus label.

When I execute my sql statement on the database server I am getting the right date format like above, but when I am looking at the exporter output it seems that the exporter converts this time format in the epoch timestamp e.g. 1523369523.

Is it possible to let the exporter not touch this date format?

**Comment by wrouesnel** [comment]
It's possible but I'm not sure its a good idea. Putting timestamps in labels isn't going to be great for Prometheus to store in it's backend - what's your use case?

**Comment by wrouesnel** [comment]
For an immediate fix you could just have your query cast the date type to a string in the output. That would mean the exporter would leave the value alone in conversion.

**Comment by jreineke-nli** [comment]
Thanks for the advice with this change the exporter imports the date as i want it to be.

Because this is a grafana issue I think this issue can be closed.
