### ISSUE TITLE
Unable to build on Centos (math/bits issue)

### ISSUE THREAD

**Issue by fhilpert** [wrouesnel/postgres_exporter#183]
Hi, 

I'm unable to build your exporter on Centos 7. 

Here is output : 

```
[root@VM18 postgres_exporter]# go run mage.go
Error: failed to check types in directory: magefile.go:23:2: could not import math/bits (cannot find package "math/bits" in any of:
	/root/go/src/github.com/wrouesnel/postgres_exporter/vendor/math/bits (vendor tree)
	/usr/lib/golang/src/math/bits (from $GOROOT)
	/root/go/src/math/bits (from $GOPATH))
exit status 1
```
This library exists on system on this path `/usr/lib/golang/src/math/bits.go`

So in order to help Mage I tried to create bits subfolder and copied bits.go file within it but this do not seems to help : 

```
[root@VM18 postgres_exporter]# ll /usr/lib/golang/src/math/bits/bits.go 
-rw-r--r--. 1 root root 1835 May 24  2017 /usr/lib/golang/src/math/bits/bits.go
[root@VM18 postgres_exporter]# go run mage.go
Error: failed to check types in directory: magefile.go:149:39: undeclared name: bits
exit status 1
```

The only thing I need is a binary, could you please provide it ? 

Best regards, 
Fred

**Comment by flaviosteimacher** [comment]
I update golang to 1.9.4 version and this error are fixed.

**Comment by mrechte** [comment]
Hello,
I too have the problem.
```
$ go version
go version go1.8.3 linux/amd64
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```
How would you upgrade to go 1.9 ?
Thanks
Marc

**Comment by wrouesnel** [comment]
Just download the new compiled version - https://golang.org/dl/
