### ISSUE TITLE
Binary build correction

### ISSUE THREAD

**Issue by zjagust** [wrouesnel/postgres_exporter#196]
Hello,

I noticed that the default make file behavior does not build the binary unless you specify to build one as a "parameter", whereas this line:

```
$ go run mage.go
```
should be replaced with this one in README.md:
```
$ go run mage.go binary
```

I was running this on Ubuntu 16.04 with Go version 1.9.1, and I dont know is this the case with other distros/go versions.

**Comment by beaEpoch** [comment]
me too, encountered this issue

**Comment by wrouesnel** [comment]
Fixed by c2866fd
