### ISSUE TITLE
Using queries.yaml with docker-compose

### ISSUE THREAD

**Issue by gauthiermartin** [wrouesnel/postgres_exporter#200]
Hi there, 

I'm currently trying to use the custom queries in queries.yaml but it does not seem to work.

Here is what i have in my docker-compose.yml

![screen](https://user-images.githubusercontent.com/7561038/41779806-f0f69b76-7600-11e8-9cff-d46e90956ec5.png)

I does seem the file is not loaded upon launching the container.

Could you provide any example ?

**Comment by ganievs** [comment]
Hi @gauthiermartin! Can you add ```--log.level="debug"``` into command and send the following debug information

**Comment by wrouesnel** [comment]
Yeah that looks like it should work just fine - you need to check the logs to see it's all where you expect.

**Comment by gauthiermartin** [comment]
Thank you that did the trick
