### ISSUE TITLE
Converting boolean data types from database to 1.0 and 0.0 value metrics?

### ISSUE THREAD

**Issue by miguelHx** [wrouesnel/postgres_exporter#201]
I run into this INFO log when trying to bring in a boolean data type from the postgres db:

```INFO[0088] Unparseable column type - discarding:  pg_importer_table success <nil>```

After a little investigation, it seems that the exporter does not handle float conversion of boolean data types.  I was thinking we can slap an if statement giving it a 1.0 if true, 0.0 otherwise.  This would be useful to track in Prometheus, especially for alerting when a value becomes true/false.

Is this something that can be incorporated?  I wouldn't mind sending in a PR, just wanted to see get some feedback from anyone.

**Comment by wrouesnel** [comment]
This seems reasonable, but the PR has linter errors preventing it from being merged at the moment.
