### ISSUE TITLE
Does the exporter support https query?

### ISSUE THREAD

**Issue by lily-liang-01** [wrouesnel/postgres_exporter#204]
and more, will the exporter supports access control later? seems anyone can access the metrics url withouth user authentication?

**Comment by wrouesnel** [comment]
This is considered out of scope for the exporter. I solve this problem with a separate exporter which handles this type of proxying - https://github.com/wrouesnel/reverse_exporter

Another way is to use nginx. In both cases, if you need to secure the exporter generally then you need a much more significant design which it's not practical to support in every exporter.
