### ISSUE TITLE
queries.yaml: no such file or directory" source="postgres_exporter.go:959

### ISSUE THREAD

**Issue by Codenxp** [wrouesnel/postgres_exporter#209]
When running docker with extend.query-path, an error is reported as below and container can run normally. Same CML works well on July 31.

`docker run -p 9187:9187 --name postgres -e DATA_SOURCE_NAME="postgresql://ddauser1:**@ec2-52-4-235-100.compute-1.amazonaws.com:5432/LearnDatabase?sslmode=disable"  wrouesnel/postgres_exporter  --extend.query-path=/Users/nning/go/src/github.com/wrouesnel/postgres_exporter/queries.yaml 

time="2018-08-20T09:06:10Z" level=info msg="Established new database connection." source="postgres_exporter.go:1005"
time="2018-08-20T09:06:11Z" level=info msg="Semantic Version Changed: 0.0.0 -> 9.4.7" source="postgres_exporter.go:935"
time="2018-08-20T09:06:11Z" level=error **msg="Failed to reload user queries: /Users/nning/go/src/github.com/wrouesnel/postgres_exporter/queries.yaml open /Users/nning/go/src/github.com/wrouesnel/postgres_exporter/queries.yaml: no such file or directory" source="postgres_exporter.go:959"**
time="2018-08-20T09:06:13Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1148"
`
permission of file queries.yaml is 644.
Is there anyone has encountered this issue?

**Comment by alpaslanakdag** [comment]
How did you solve this problem. I have the same issue.
