### ISSUE TITLE
Exporter does not exit if failed to connect to DB

### ISSUE THREAD

**Issue by ghost** [wrouesnel/postgres_exporter#213]
I have an issue case where postgres exporter container is starting before Postgresdb. Obviously it will fail to connect. I am expecting the exporter to try connecting in loop till it succeeds. Or atleast it has to exit if it fails to connect, so that it can restart once DB is up. Is it possible?
Also I was trying for different solution to mount my script into the container which causes container to wait till DB is up. This also does not seem working. 
What is the way I could handle this? Thanks.

**Comment by silentpete** [comment]
**Environment**
Start a docker compose with the defaults shown in the README.md, but using a tag on the image so we know which version we're working with. (wrouesnel/postgres_exporter:v0.4.7)

**Walkthrough**
The initial logs from the exporter shows it didn't make a connection...
```
$ docker logs postgres_exporter
time="2019-01-10T19:27:23Z" level=info msg="Established new database connection." source="postgres_exporter.go:1035"
time="2019-01-10T19:27:24Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1041"
time="2019-01-10T19:27:24Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@postgres:5432/postgres?sslmode=disable): dial tcp 172.28.0.3:5432: connect: connection refused" source="postgres_exporter.go:1070"
time="2019-01-10T19:27:24Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1178"
```
This is correct, as postgres wasn't completely up before the postgres_exporter tried to connect.

The postgres_exporter continues on it's way and waits, it does not exit, as it is waiting to respond to requests. (such at prometheus scraping)

If you curl the metrics endpoint, it will attempt to connect to postgres each time. This is the metrics collection mechanism.
```
$ curl -s localhost:9187/metrics
```
After curl'ing the endpoint, you can now see it connected in the logs.
```
$ docker logs postgres_exporter
time="2019-01-10T19:27:23Z" level=info msg="Established new database connection." source="postgres_exporter.go:1035"
time="2019-01-10T19:27:24Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1041"
time="2019-01-10T19:27:24Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@postgres:5432/postgres?sslmode=disable): dial tcp 172.28.0.3:5432: connect: connection refused" source="postgres_exporter.go:1070"
time="2019-01-10T19:27:24Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1178"
time="2019-01-10T19:33:36Z" level=info msg="Established new database connection." source="postgres_exporter.go:1035"
time="2019-01-10T19:33:36Z" level=info msg="Semantic Version Changed: 0.0.0 -> 11.1.0" source="postgres_exporter.go:965"
```

**Helpful Note**
There is a metric that can be used to know if the connection is up or down
```
$ curl -s localhost:9187/metrics | grep "pg_up"
# HELP pg_up Whether the last scrape of metrics from PostgreSQL was able to connect to the server (1 for yes, 0 for no).
# TYPE pg_up gauge
pg_up 1
```

**Conclusion**
The postgres_exporter is working as designed in my opinion. You can test stopping postgres and look at the metrics change as well, which pg_up will change. Hope this helped.

Peter

**Comment by wrouesnel** [comment]
"Die if you can't initially connect" was originally a feature to ensure that config deployments could detect a failing postgres_exporter. The feature is gone now since we now have pg_up to poll instead.
