### ISSUE TITLE
Add support for postgres10

### ISSUE THREAD

**Issue by jayson-wang** [wrouesnel/postgres_exporter#214]
After installing the latest version of postgresql server 10.5, I started postgres_exporter . According to the error message, postgresql's  version 10 is not supported at present 

INFO[0148] Error running query on database:  pg_stat_replication pq: function pg_current_xlog_location() does not exist
  source=postgres_exporter.go:917

The official documentation says that the name of this function was changed in versions 9 and 10

https://wiki.postgresql.org/wiki/New_in_postgres_10

9.6 Function Name | 10 Function Name
-- | --
pg_current_xlog_flush_location | pg_current_wal_flush_lsn
pg_current_xlog_insert_location | pg_current_wal_insert_lsn
pg_current_xlog_location | pg_current_wal_lsn
pg_is_xlog_replay_paused | pg_is_wal_replay_paused
pg_last_xlog_receive_location | pg_last_wal_receive_lsn
pg_last_xlog_replay_location | pg_last_wal_replay_lsn
pg_switch_xlog | pg_switch_wal
pg_xlog_location_diff | pg_wal_lsn_diff
pg_xlog_replay_pause | pg_wal_replay_pause
pg_xlog_replay_resume | pg_wal_replay_resume
pg_xlogfile_name | pg_walfile_name
pg_xlogfile_name_offset | pg_walfile_name_offset

**Comment by palmerabollo** [comment]
Is this already implemented? I see a `pg_stat_replication_pg_xlog_location_diff` metric available using Postgres 9.x and a different `pg_stat_replication_pg_wal_lsn_diff` using Postgres 10, but perhaps I'm missing something.

**Comment by ptman** [comment]
I don't know what I'm doing differently, but I have it working with postgres 11

**Comment by wrouesnel** [comment]
This should be working - Postgres 10 is included as part of the standard test suite for the CI.

**Comment by macnibblet** [comment]
@wrouesnel It works, but it's throwing a lot of errors in the postgreql logs

**Comment by wrouesnel** [comment]
So far nothing more to be done with this.
