### ISSUE TITLE
get metrics for pg_stat_activity using non-superuser

### ISSUE THREAD

**Issue by zhanggbj** [wrouesnel/postgres_exporter#217]
Hi,

currently all the metrics in  pg_stat_activity is **0**,  and this is expected as I connect to postgres using an user which is not a superuser. Then I came accorss the guide here.
https://github.com/wrouesnel/postgres_exporter#running-as-non-superuser'

However I have **no** credential for any `superuser` in my DB, is there any other options to get the metrics in `pg_stat_activity`.

**Comment by keithf4** [comment]
You're going to need a superuser account of some sort if you're going to want to grant those access abilities to others. Otherwise, that's kind of a huge security hole if you can just gain access to things you shouldn't be able to otherwise.

**Comment by wrouesnel** [comment]
Generally the solution is to assign a view as outlined in the README.md, though full disclosure is I've never actually had to do this for my own deployments - the advice was contributed by others.

**Comment by barrowkwan** [comment]
Following the README.md to create the view but I am still getting empty result from DB.  this is postgresql 9.6

**Comment by arcalys** [comment]
As of 10.x, you can use the pg_read_all_stats role, e.g.:
```sql
grant pg_read_all_stats to postgres_exporter;
```

https://www.postgresql.org/docs/10/default-roles.html

**Comment by knweiss** [comment]
Given a postgresql 9.3 DBMS I've tried the [solution from the README.md](https://github.com/wrouesnel/postgres_exporter#running-as-non-superuser), too. However, it also have problems:

Using the `postgres_exporter` user I'm able to count. However, e.g. the `state` column of most rows is empty and the `query` column shows "insufficient privilege".
```
postgres=> select count(*) from postgres_exporter.pg_stat_activity;  
 count
-------
     7
(1 row)

postgres=> select datname,state,query from postgres_exporter.pg_stat_activity;
  datname   | state  |                                query
------------+--------+---------------------------------------------------------------------
 aaaa       |        | <insufficient privilege>
 bbbb       |        | <insufficient privilege>
 aaaa       |        | <insufficient privilege>
 aaaa       |        | <insufficient privilege>
 postgres   | active | select datname,state,query from postgres_exporter.pg_stat_activity;
 postgres   |        | <insufficient privilege>
 postgres   |        | <insufficient privilege>
(7 rows)
```

**Comment by ThomasPoty** [comment]
Hello,
You should create a function which returns results of select * from
pg_stat_activity ( with security definer ( the definer must be a superuser))
Then, you create a view which call that function.
in your yaml file you work with the view.

Le mer. 6 févr. 2019 à 16:17, Karsten Weiss <notifications@github.com> a
écrit :

**Comment by knweiss** [comment]
Update: The stored procedure variant (see #95) works for me (psql 9.3).
