### ISSUE TITLE
Grafana Dashboard?

### ISSUE THREAD

**Issue by Drewster727** [wrouesnel/postgres_exporter#218]
https://grafana.com/dashboards/3742

Does anyone know if this dashboard still works with this exporter?
I've got the exporter loaded, pg_stat_statements enabled, and it's still not working...

Anyone have any ideas or have a better grafana dashboard they can share?

I'm using postgresql 10.5 with the latest postgres_exporter.

Thank you!

**Comment by uspen** [comment]
This is bad dashboard

**Comment by anarcat** [comment]
what's wrong with that dashboard exactly?

anyways, for those of us looking at dashboards, I have found that the [most downloaded one](https://grafana.com/dashboards/455) works okay, even though it's very basic. There a [bunch more dashboards](https://grafana.com/dashboards?dataSource=prometheus&search=postgres) and I would love to hear from other users which one is their favorite.

**Comment by nchudleigh** [comment]
Found a trove of really good dashboards, here -> https://github.com/percona/grafana-dashboards

This one is in the collection and is really awesome, blows any that are on the marketplace out of the water -> https://github.com/percona/grafana-dashboards/blob/master/dashboards/PostgreSQL_Overview.json

The marketplace is generally really bad, all the best ones I have found have been directly from github repositories.  Only the most popular ones from the marketplace are any good.

@Drewster727 Perhaps you could submit a PR that lists this repo/dashboard in the README?

**Comment by anarcat** [comment]
`PostgreSQL_Overview.json` is interesting, but i find it a little overwhelming. I have found the one on the grafana dashboards site to be mostly okay, although I had to [tweak it](https://gitlab.com/anarcat/grafana-dashboards/blob/master/postgresql.json) to make it do what i wanted.

**Comment by pitabwire** [comment]
Some good dashboards exist [here](https://promcat.io/apps/postgresql#Dashboard) as well

**Comment by gajus** [comment]
Is there a dashboard that would provide query level insights?
