### ISSUE TITLE
Port 9113 is reserved for  nginx_exporter

### ISSUE THREAD

**Issue by mjtrangoni** [wrouesnel/postgres_exporter#22]
You probably should reserve another Port by _Prometheus_, because the 9113 is already reserved for the [nginx_exporter](https://github.com/discordianfish/nginx_exporter). See [Default-port-allocations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations).

**Comment by wrouesnel** [comment]
It wasn't always :(

Looks like 9187 would be the appropriate number to adopt.
