### ISSUE TITLE
connect string

### ISSUE THREAD

**Issue by skad0Osh** [wrouesnel/postgres_exporter#221]
Incase we have multiple databases per PGSID, what database should we use for the connect string? 
If we use default database postgres, data for  database specific stats like pg_stat_user_tables does not include data from all the databases. Should we run one exporter per database?

**Comment by wrouesnel** [comment]
One exporter per DB was the original design. There is now multi-DB support, and some support for master->extra databases.

`queries.yml` is an area of the code I've only ever had very limited use for personally but got superuseful to everyone else.
