### ISSUE TITLE
do i need to have docker 

### ISSUE THREAD

**Issue by Vitthal4288264** [wrouesnel/postgres_exporter#227]
I am running postgres_exporter in windows it is giving following error

Error while closing non-pinging DB connection: <nil>  [36msource[0m="postgres_exporter.go:1001"
[36mINFO[0m[0004] Error opening connection to database (postgresql://:PASSWORD_REMOVED@): pq: SSL is not enabled on the server  [36msource[0m="postgres_exporter.go:1030".

please do help thanks.

**Comment by wrouesnel** [comment]
Docker is not required. Generally you need to build the connection string with [lib/pq](https://github.com/lib/pq) compatible syntax.
