### ISSUE TITLE
"B" is a valid unit and should be accepted

### ISSUE THREAD

**Issue by Jean-Daniel** [wrouesnel/postgres_exporter#228]
Using postgresql 11, the exporter crash immediately with the error:

    panic: Unknown unit for runtime variable: "B"

While there is a lots of units supported by the exporter, surprisingly"B" is not one of them.

**Comment by wrouesnel** [comment]
Released as a part of https://github.com/wrouesnel/postgres_exporter/releases/tag/v0.4.7

**Comment by phumpal** [comment]
:+1: thanks!
