### ISSUE TITLE
postgres_exporter_v0.4.5_linux-amd64 related issue

### ISSUE THREAD

**Issue by omagrawal007** [wrouesnel/postgres_exporter#229]
time="2018-11-01T10:54:27Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1001"
prometheusexporter_1  | time="2018-11-01T10:54:27Z" level=info msg="Error opening connection to database (could not parse DATA_SOURCE_NAME): pq: Could not detect default us

**Comment by ptman** [comment]
What does your `DATA_SOURCE_NAME` look like?

**Comment by omagrawal007** [comment]
postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@postgres:5432?sslmode=disable

**Comment by ptman** [comment]
@omagrawal007 that defines the db host, but not the db name:

    DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"

Note postgresql:// and /postgres
