### ISSUE TITLE
Absolute link in postgres_exporter-0.4.7/tools/src

### ISSUE THREAD

**Issue by freaknils** [wrouesnel/postgres_exporter#239]
Hi,

in the source tar of version 0.4.7 is absolute link in _postgres_exporter-0.4.7/tools/_ pointing on _/home/will/src/go/src/github.com/wrouesnel/postgres_exporter/tools/vendor_

I think this is an mistake

**Comment by wrouesnel** [comment]
It gets wiped by the build process anyway, but I suppose I should remove it at some point.
