### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by nishant65563** [wrouesnel/postgres_exporter#241]
I'm using docker and I've run:

docker run --net=host -it --rm -e POSTGRES_PASSWORD=password postgres

which kicks it off but then when i run:

docker run --net=host -e DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" wrouesnel/postgres_exporter

I get: standard_init_linux.go:195: exec user process caused "exec format error"

**Comment by baryluk** [comment]
OS? CPU? Try again?

**Comment by wrouesnel** [comment]
All docker images are amd64 binary based. arm images are not published.

**Comment by viggy28** [comment]
@wrouesnel wondering if `arm` in the pipeline? Any technical challenges that I need to be aware of if I try to build it on arm?
