### ISSUE TITLE
Build with go modules

### ISSUE THREAD

**Issue by ddevault** [wrouesnel/postgres_exporter#242]
It would be nice to be able to `go build` this, assuming it's possible.

**Comment by DeathBorn** [comment]
Yeah... by my taste, provided way of building this is really non standard and quite nasty. Anyway. @ddevault if you want to do `go build` just run it in `cmd/postgres_exporter` dir

**Comment by wrouesnel** [comment]
As noted, go build works provided you point it at the command (it is in fact how the magefile based build works under the hood).

I'm not a fan of how go modules is turning out so far, and the exporter is simple enough that it doesn't need anything more complicated - the automation works well for me.
