### ISSUE TITLE
Metrics for the time spent on all SQLs execution

### ISSUE THREAD

**Issue by LizZzxx** [wrouesnel/postgres_exporter#251]
Hi,
    This exporter helps me a lot!
    But I have a question: Is a metric for the duration of all the SQLs execution available in this exporter tool?

 Expect for your answer, thanks!

**Comment by regeda** [comment]
Hi
As I know the exporter returns how much tuples was affected for each SQL. You should export custom metrics from your app if you need the duration of queries.

**Comment by baryluk** [comment]
Afaik Postgres server is not tracking this information by default, so exporter can't really export it. It is indeed best to export data directly from application. Benefit is that you can build latency histograms easier this way, and bucket different SQL queries separately by hand. (i.e. it makes little sense to track very fast and very slow queries in single metric like average without any breakdown).

**Comment by wrouesnel** [comment]
pg_stat_activity metrics are now in `queries.yml`. If you can setup a metric for it'll work.
