### ISSUE TITLE
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name

### ISSUE THREAD

**Issue by mikezsin** [wrouesnel/postgres_exporter#254]
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "pg_settings_archive_timeout_seconds", help: "Forces a switch to the next WAL file if a new file has not been started within N seconds. [Units converted to seconds.]", constLabels: {server="db.server:5432"}, variableLabels: []}

postgres_exporter v0.4.7-22-g6d2cae6 (built with go1.11.4)
server 9.6.3
 archive_timeout | 60

**Comment by mikezsin** [comment]
fail only with multi datasource configuration

**Comment by regeda** [comment]
DId try to disable settings metrics `disable-settings-metrics`?

**Comment by regeda** [comment]
It happens when you setup scraping from two different postgres versions

**Comment by mikezsin** [comment]
> DId you try to disable settings metrics `disable-settings-metrics`?
yes, it works

**Comment by regeda** [comment]
@mikezsin Great
