### ISSUE TITLE
multi server exporter - label

### ISSUE THREAD

**Issue by uspen** [wrouesnel/postgres_exporter#255]
Hello!
Can you add custom label or cluster_name from pg_settings for every metric by DSN?

See: https://github.com/wrouesnel/postgres_exporter/pull/215#issuecomment-448934315

**Comment by regeda** [comment]
What do you propose? Replace `host:port` string by `cluster_name` or just add the label within `host:port`.

**Comment by wrouesnel** [comment]
Urgh, I wasn't a huge fan of complicating the exporter to do multiple servers or DBs in the first place because this is the can of worms it tends to open. PRs will be accepted if they resolve this in an optional way.
