### ISSUE TITLE
Change default value of checkpoint_completion_target to 0.9 for better performance?

### ISSUE THREAD

**Issue by HCHCHH** [wrouesnel/postgres_exporter#257]
The Postgre [official document](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) recommends to set **checkpoint_completion_target** to **0.9**, which is the more useful value and improves the performance.
"You can spread those writes out further, lowering the average write overhead, by increasing the checkpoint_completion_target parameter to its **useful maximum of 0.9** (aim to finish by the time 90% of the next checkpoint is here) **rather than the default of 0.5** (aim to finish when the next one is 50% done).  ". 

I wonder if the default need to be changed for performance concern. Thanks.

**Comment by baryluk** [comment]
This have nothing to do with `postgres_exporter`.

**Comment by wrouesnel** [comment]
Indeed, postgres_exporter shouldn't be writing anything (which is interesting, because you could probably abuse queries.yml to have it do this - please don't).
