### ISSUE TITLE
How to get metric from queries.yaml

### ISSUE THREAD

**Issue by LizZzxx** [wrouesnel/postgres_exporter#259]
Hi,
   May you show how to get the metrics from the queries.yaml?

Regarding your answer!
Thanks!

**Comment by baryluk** [comment]
The top level key name is the name of the metric. Check the example `queries.yaml` file in the repo.

**Comment by goldfishalpha** [comment]
I have a similar question.
I am trying to run this with docker-compose.
Inputting `pg_database_size` into prometheus query search returns  **_no data_**

Is this similar to #249, whereby it is not yet in released version

p.s. Default queries return data where applicable

**Comment by wrouesnel** [comment]
`pg_database_size` requires the default queries.yml file, it is not a built in metric due to the potential cost.

It will be changing to `pg_database_size_bytes` soon.
