### ISSUE TITLE
Units and _total suffixes for metric names.

### ISSUE THREAD

**Issue by baryluk** [wrouesnel/postgres_exporter#261]
https://prometheus.io/docs/practices/naming/#metric-names

The biggest issue is with the metrics that are time, it is really hard to guess if they are seconds or something else.

Would be great if they end in proper units, `pg_stat_database_blk_read_time_msec`, `pg_stat_activity_max_tx_duration_seconds`.

Some others like _bytes, could be useful to be in metric name too, but not as important (they are more obvious).

**Comment by wrouesnel** [comment]
I've merged some progress on this for queries.yml. There is a tension between changing the name of well-known metrics to make them conform, vs. reformatting the metric to bring it to Prometheus standard etc.

At this point I'd be hesitant to change built-in metric names.
