### ISSUE TITLE
[Help Wanted] Endpoint Timeout Issue

### ISSUE THREAD

**Issue by bp32795** [wrouesnel/postgres_exporter#265]
I followed the documentation to launch the exporter with docker and from what I can tell it is running successfully. However, when I try to hit <myIPaddress>:9187/metrics, I just get a timeout error. Where should I set prometheus to scrape?

**Comment by regeda** [comment]
Could you provide more information about the console output? What the program reports.

**Comment by wrouesnel** [comment]
Not enough info to action.
