### ISSUE TITLE
panic: interface conversion: interface {} is string, not map[interface {}]interface {}

### ISSUE THREAD

**Issue by tszilv** [wrouesnel/postgres_exporter#268]
Hi,

I try to use postgres exporter with extended.query_path.

I f I start postgres exporter , it appears in prometheus, and work fine.
If would like to use query.yaml I got error, see under.
I dont use docker only single machine. postgres version is 11.
Postgres exporter version:
postgres_exporter v0.4.7 (built with go1.10)

./postgres_exporter --extend.query-path=./program/query.yaml --log.level=debug

INFO[0000] Established new database connection.          source="postgres_exporter.go:1035"
DEBU[0000] Querying Postgres Version                     source="postgres_exporter.go:948"
INFO[0000] Semantic Version Changed: 0.0.0 -> 11.2.0     source="postgres_exporter.go:965"
DEBU[0000] replay_location is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] procpid is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] write_location is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] pg_xlog_location_diff is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] flush_location is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] sent_location is being forced to discard due to version incompatibility.  source="postgres_exporter.go:504"
DEBU[0000] New user metric namespace from YAML: pg_stat_user_tables  source="postgres_exporter.go:402"
DEBU[0000] New user metric namespace from YAML: pg_statio_user_tables  source="postgres_exporter.go:402"
DEBU[0000] New user metric namespace from YAML: pg_database  source="postgres_exporter.go:402"
DEBU[0000] New user metric namespace from YAML: description  source="postgres_exporter.go:402"
panic: interface conversion: interface {} is string, not map[interface {}]interface {}

goroutine 19 [running]:
main.addQueries(0xc4201aca00, 0x11ba, 0x13ba, 0xb, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

Regards,

Szilvia

**Comment by regeda** [comment]
Could you try the same with the master branch?

**Comment by tszilv** [comment]
I downloded query.yaml file from the internet, and it has got some unvisible character(s), I changed the yaml file contentents, and now it works.
