### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by UnderGreen** [wrouesnel/postgres_exporter#27]
Hello!

At first, thank you and all contributors for your great job!

Can you release new version and publish new binaries? I need feature about select from yaml file and I am using Ansible role which needs to have URL for latest binary.
I can for, build, release new version and working with my fork. But it's not a true way. :)

Thank you, @wrouesnel.

**Comment by arypurnomoz** [comment]
I have the same situation. It would be great if the latest release is available in binary!

**Comment by wrouesnel** [comment]
There's a few open issues I need to resolve first, which requires a clean up of the CI test builds to make sure I cover off first.

**Comment by wrouesnel** [comment]
Released version 0.1.1 yesterday and published to docker.

**Comment by arypurnomoz** [comment]
@wrouesnel  thank you! 👍
