### ISSUE TITLE
Help about the syntax for the environment variable DATA_SOURCE_NAME for multiple database

### ISSUE THREAD

**Issue by chhith** [wrouesnel/postgres_exporter#273]
Hi,
I'm trying postgres_exporter for Prometheus. I need some help about the syntax for the DATA_SOURCE_NAME variable in the case we have multiple database in one instance.

On my postgresql server, I have 2 database (Bills and Customers).
It worked when I set DATA_SOURCE_NAME with a single DB like this :
export DATA_SOURCE_NAME="postgresql://login:password@localhost:5432/bills?sslmode=disable" 
or
export DATA_SOURCE_NAME="postgresql://login:password@localhost:5432/customers?sslmode=disable

But I got those messages error when I set the DATA_SOURCE_NAME like this :
export DATA_SOURCE_NAME="postgresql://login:password@localhost:5432/bills?sslmode=disable,postgresql://login:password@localhost:5432/customers?sslmode=disable"

INFO[0000] Established new database connection.          source="postgres_exporter.go:1035"
INFO[0000] Error while closing non-pinging DB connection: <nil>  source="postgres_exporter.go:1041"
INFO[0000] Error opening connection to database (postgresql://login:PASSWORD_REMOVED@localhost:5432/bills?sslmode=disable,postgresql://login:password@localhost:5432/customers?sslmode=disable): pq: unsupported sslmode "disable,postgresql://postgres:postgres@localhost:5432/postgres2?sslmode=disable"; only "require" (default), "verify-full", "verify-ca", and "disable" supported  source="postgres_exporter.go:1070"

Could you help me with the correct syntax please ? O should I launch one exporter per database ?

I'm grateful in advance :)

Kinds

**Comment by pedroetb** [comment]
You are providing 2 sources, and the `sslmode` parameter of the first one, is getting as value the string `disable,postgresql://postgres:postgres@localhost:5432/postgres2?sslmode=disable`. Try to define disabled between quotes (I used single quotes, `sslmode='disable'`).

**Comment by chhith** [comment]
Hey, thx for the reply :) 
So, Is it not possible to provide 2 sources in the Data_source_name ?

**Comment by pedroetb** [comment]
Yes, for example:
```
export DATA_SOURCE_NAME="postgresql://login:password@localhost:5432/bills?sslmode='disable',postgresql://login:password@localhost:5432/customers?sslmode='disable'"
```

**Comment by chhith** [comment]
Hi pedroetb, 

thanks for the reply :)

So, What could I do if I need to use the exporter for multiple DB instance ?

**Comment by pedroetb** [comment]
Hi @chhith,
if you read carefully my last reply, you will see that DATA_SOURCE_NAME contains 2 different postgresql sources, separated by comma. These sources can belong to different DB instances.

**Comment by regeda** [comment]
What version of the exported do you use? The only `master` branch version contains the feature to scrap multiple instances from a single exporter process.

**Comment by viggy28** [comment]
Hi @pedroetb, tried your example but still getting the same error as OP posted.

@regeda, mind sharing your DSN? Thanks.

**Comment by wrouesnel** [comment]
0.6.0 has been released today which includes all these features (looking at an 0.7.0 very soon since I'm finally clearing out the PR backlog...)
