### ISSUE TITLE
Usage of pg_stat_user_tables from queries.yaml

### ISSUE THREAD

**Issue by ahes** [wrouesnel/postgres_exporter#284]
What is the suggested way of getting `pg_stat_user_tables` metrics for particular database? 

1. Should I include database name somewhere in the query? Is it even possible to change database name there?
2. or maybe I should run additional `postgres_exporter` process with `--disable-default-metrics` and `--disable-settings-metrics`,  include YAML file with stat query and set my database name in DATA_SOURCE_NAME env variable?

**Comment by ahes** [comment]
I will answer myself. It seems you can specify additional `database=` in `DATA_SOURCE_NAME` variable. For example:

```
DATA_SOURCE_NAME="user=postgres host=/var/run/postgresql/ sslmode=disable database=postgres database=my_production_database"
```

I think it should be pointed out in README.

**Comment by sergeypugachov** [comment]
Also,  i think it can be used with --auto-discover-databases
