### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by wys35** [wrouesnel/postgres_exporter#288]
I am getting the below error while trying to build on Windows. 
PS > go run mage.go binary 
2019/07/13 07:31:38 exec: git describe --dirty                                                                          
2019/07/13 07:31:38 exec: git describe --abbrev=0                                                                       2019/07/13 07:31:38 exec: go list ./...                                                                                 
Finished 1 of 6                                                                                                         
Finished 2 of 6                                                                                                        
Finished 3 of 6                                                                                                         
Finished 4 of 6                                                                                                         
Finished 5 of 6                                                                                                         
Finished 6 of 6                                                                                                         
Error: mkdir C:\Users\wu_yu\go\src\github.com\wrouesnel\postgres_exporter\bin/C:: The filename, directory name, or volume label syntax is incorrect.                                                                                            exit status 1

**Comment by wrouesnel** [comment]
Without more info I'm not sure what's happening here. The magefile build code doesn't use manual path specifiers anywhere, although it does like creating directories with underscores.
