### ISSUE TITLE
[Feature Request] Support for Hashicorp Vault/refreshing credentials.

### ISSUE THREAD

**Issue by kanuahs** [wrouesnel/postgres_exporter#290]
I want to run postgres exporter as a kubernetes pod. PostgresSQL usernames & passwords are generated by vault and expire after a certain amount of time.

I was planning on using a sidecar to fetch credentials and inject them into the exporter container as environment variables. However I'd like to avoid restarting the pod to use the updated credentials.

Possible fix:
On db connection failure, the exporter could refresh credentials and retry if a change is detected.

**Comment by wrouesnel** [comment]
The pod shouldn't need to be restarted, just the exporter. This is ultimately an issue of complexity - the exporter is fairly lightweight, and shouldn't have any problems being restarted.

I'd accept a PR which resolved this, but I don't use the system this way myself so I'm uncomfortable changing it.
