### ISSUE TITLE
Blacklist/Whitelist for --auto-discover-databases

### ISSUE THREAD

**Issue by AlexisSellier** [wrouesnel/postgres_exporter#295]
I have been using the option `--auto-discover-databases`, which is handy, but I got errors when fetching databases like template0, rdsadmin ...

I implement a blacklist/whitelist option to not scrape those databases and get ride of the errors.

It this something that would interest you to be merged ?

**Comment by keithf4** [comment]
I second a feature like this. But `--auto-discover-databases` should not be connecting to template databases or any databases that are set to not allow connections anyway.

**Comment by AlexisSellier** [comment]
I agree with you. I have made a [PR](https://github.com/wrouesnel/postgres_exporter/pull/297) to not have templates nor databases inside of the result when using `--auto-discover-databases`
