### ISSUE TITLE
pg_replication_slots.active_pid does not exist

### ISSUE THREAD

**Issue by ncabatoff** [wrouesnel/postgres_exporter#30]
Pull request #23 has introduced a regression: the query against pg_stat_replication now joins with pg_replication_slots on pg_stat_replication.pid=pg_replication_slots.active_pid.  But pg_replication_slots.active_pid is not a valid column, see https://www.postgresql.org/docs/9.4/static/catalog-pg-replication-slots.html.  In light of that and the fact that pg_replication_slots is only present in 9.4 (not in 9.2, 9.5, etc) I suggest reverting this change altogether.

**Comment by ncabatoff** [comment]
I forgot to include the error output:

INFO[0000] Error running query on database:  pg_stat_replication pq: column pg_replication_slots.active_pid does not exist  source=postgres_exporter.go:624

**Comment by wrouesnel** [comment]
Related to #29

We're probably past the point where we need to be enable/disable some of the checks.

**Comment by ncabatoff** [comment]
I'm inclined to factor out all the existing queries into the YAML file, giving the user full control.

**Comment by wrouesnel** [comment]
I'm not so enthusiastic about the YAML - the goal of the exporter is to try and be as plug and play as possible. The YAML is more a nod to the special cases when you need just a little bit more, but don't want an application specific exporter.
