### ISSUE TITLE
Dublicate database connection when used --auto-discover-databases

### ISSUE THREAD

**Issue by sfalkon** [wrouesnel/postgres_exporter#308]
When I used option --auto-discover-databases, database get dublicate connection.

![dublicate](https://user-images.githubusercontent.com/10250625/65257505-fac65000-db09-11e9-9ed5-51adf92f58e2.png)

Maybe you neeed change query in function queryDatabases(server *Server) ([]string, error)
Old query:  "SELECT datname FROM pg_database WHERE datallowconn = true AND datistemplate = false"
New query (for excluding current connection database): "SELECT datname FROM pg_database WHERE datallowconn = true AND datistemplate = false and datname!=current_database()"

**Comment by wrouesnel** [comment]
Resolved by #314 thank you.
