### ISSUE TITLE
Additional maintainer

### ISSUE THREAD

**Issue by AlexisSellier** [wrouesnel/postgres_exporter#312]
HI,
Do you need an extra maintainer to help you review and merge PR and qualify issues.
Since this project is directly linked from the prometheus documentation page, we should not let it sink due to a lack of activity.

Happy to help.

**Comment by iand** [comment]
Hi, I'm from @timescale and we would also like to help by reviewing code and triaging issues. We currently have an internal fork that has merged some of the outstanding PRs (such as SCRAM support) but we'd prefer to see these in the public project.

**Comment by wrouesnel** [comment]
I've merged (or updated and superceded) all the outstanding PRs. Been a bad year for me since I've been building a house.

Closing this issue for now, but it's something I definitely need to think about.

**Comment by kerams** [comment]
This should be reopened. The project has been pretty much completely neglected for at least a year.
