### ISSUE TITLE
What's the meaning of "// Is this a metricy metric?" for discards?

### ISSUE THREAD

**Issue by benjaminjb** [wrouesnel/postgres_exporter#315]
I'm a little confused about the ColumnUsage "Discard" and particularly the code comment here:

https://github.com/wrouesnel/postgres_exporter/blob/238f5c099af62ec32fb7c511361fd616e3998f2f/cmd/postgres_exporter/postgres_exporter.go#L1175-L1178

From the tests, I understand the usage of semver comparison to discard certain stats, i.e., PG version <=9 might have a different stat from >9, so if the comparison shows you have 9, discard the stats above 9.

But what's the use case for the ColumnUsage "Discard" and what's the meaning of a "metricy metric" in this context?

**Comment by wrouesnel** [comment]
Discard exists basically for things which aren't metrics in any meaningful way - so strings, stored byte-fields, etc. of which there are a few.

Metricy metric is just because up till that point, I regard all fields as metrics till proven otherwise.
