### ISSUE TITLE
arm64 supported?

### ISSUE THREAD

**Issue by jorkzijlstra** [wrouesnel/postgres_exporter#317]
Wondering id arm64 arch is supported or not?

When I run it on my laptop the container runs fins, but them moving the container to my Rock Pi 4B it starts failing with:

```
dsmrdb-exporter    | standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by wrouesnel** [comment]
The published container isn't built for arm64 at the moment though AFAIK there's nothing in the code which should prevent it being built for arm64.

**Comment by jorkzijlstra** [comment]
Thnx, I thought that was indeed the case, but I haven't had the time to convert this repo to a dockercross setup.

**Comment by Hades32** [comment]
FYI Bitname is building a ARM64 docker image: https://hub.docker.com/r/bitnami/postgres-exporter
