### ISSUE TITLE
cannot connect with user@host role

### ISSUE THREAD

**Issue by ssube** [wrouesnel/postgres_exporter#325]
I'm trying to connect the postgres_exporter to an Azure postgres server that requires SSL and `user@host` usernames. While `?sslmode=require` solved the former, the `@` symbol in the username seems to be a problem:

```
> kubectl -n monitoring logs timescale-watchdog-58b8dd86fc-pcfzr
time="2019-11-01T18:39:09Z" level=info msg="Established new database connection to \"build-metrics.postgres.database.azure.com:5432\"." source="postgres_exporter.go:814"
time="2019-11-01T18:39:10Z" level=info msg="Established new database connection to \"build-metrics.postgres.database.azure.com:5432\"." source="postgres_exporter.go:814"
time="2019-11-01T18:39:12Z" level=info msg="Established new database connection to \"build-metrics.postgres.database.azure.com:5432\"." source="postgres_exporter.go:814"
time="2019-11-01T18:39:16Z" level=error msg="Error opening connection to database (postgresql://metrics%!b(MISSING)uild-metrics:PASSWORD_REMOVED@build-metrics.postgres.database.azure.com?sslmode=require): pq: Invalid connection parameters specified. Check connection parameters, and try again." source="postgres_exporter.go:1403"
time="2019-11-01T18:39:16Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1576"

> kubectl -n monitoring describe pod timescale-watchdog-58b8dd86fc-pcfzr | grep DATA_SOURCE_USER
      DATA_SOURCE_USER:  metrics@build-metrics
```

Replacing the value of `DATA_SOURCE_USER` with `metrics%40build-metrics` didn't help, same error message.

**Comment by wrouesnel** [comment]
Looks like your username is tripping up the string formatter. That section of code is really in need of some careful checks (its not fun to touch due to a wrong step tending to spam passwords into logs).

**Comment by Veraticus** [comment]
Azure recommends using a different connection string format: https://docs.microsoft.com/en-us/azure/postgresql/connect-go

`"host=%s user=%s password=%s dbname=%s sslmode=require"`

Have you tried that?

**Comment by ssube** [comment]
The `host=%s user=%s` form appears to work in the console, but I no longer have Azure instances to test against.

**Comment by gibbonsjohnm** [comment]
Is there any solution to this? Running into the same problem now.
