### ISSUE TITLE
postgres_exporter not Starting Server

### ISSUE THREAD

**Issue by rushikeshs81** [wrouesnel/postgres_exporter#332]
postgres_exporter is stuck at INFO[0000] Starting Server: :9187, Any suggestion ?

./postgres_exporter --web.telemetry-path /var/opt/pgsql/metrics
INFO[0000] Established new database connection to "localhost:5432".  source="postgres_exporter.go:814"
INFO[0000] Semantic Version Changed on "localhost:5432": 0.0.0 -> 9.5.14  source="postgres_exporter.go:1335"
INFO[0000] Starting Server: :9187                        source="postgres_exporter.go:1576"
^C

**Comment by sfalkon** [comment]
Your server is OK!

How do you get metrics?

If you set "--web.telemetry-path /var/opt/pgsql/metrics", you should call URL: localhost:9187/var/opt/pgsql/metrics

For example:
```BASH
curl -s http://localhost:9187/var/opt/pgsql/metrics
```

Because "web.telemetry-path" it is not path on disk, it's path in url.

Sorry for my english )

**Comment by rushikeshs81** [comment]
Hi Sfalkon

I really appreciate your response on this.

I thought it was stuck but it was running , I am all set. Thanks.


Thanks.

Rushikesh Socha
Edison,NJ,USA
Cell : +1 860 794 4643
