### ISSUE TITLE
Error when try start postgres_exporter v0.7.0

### ISSUE THREAD

**Issue by SergeSpinoza** [wrouesnel/postgres_exporter#335]
Hi! 

I have try to start postgres_exporter v0.7.0 with postgres 9.6.15 (on the same server) and have error: 

```
Nov 15 14:52:04 dev-db2 systemd[1]: Started postgres_exporter - Exporter for machine metrics..
Nov 15 14:52:04 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:04+03:00" level=info msg="Established new database connection to \"/var/run/postgresql/:5432\"." source="postgres_exporter.go:814"
Nov 15 14:52:05 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:05+03:00" level=info msg="Semantic Version Changed on \"/var/run/postgresql/:5432\": 0.0.0 -> 9.6.15" source="postgres_exporter.go:1335"
Nov 15 14:52:11 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:11+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:11 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:11+03:00" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1576"
Nov 15 14:52:19 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:19+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:25 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:25+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:31 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:31+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:37 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:37+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:43 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:43+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:49 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:49+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:52:55 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:52:55+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
Nov 15 14:53:01 dev-db2 postgres_exporter[3574]: time="2019-11-15T14:53:01+03:00" level=error msg="Error opening connection to database (test1): malformed dsn \"test1\"" source="postgres_exporter.go:1403"
```

and exporter on port 9187 answer very slow. 

Systemunit startup script: 

```
[Unit]
Description=postgres_exporter - Exporter for machine metrics.
Documentation=https://github.com/prometheus/postgres_exporter
After=network.target

[Service]
User=postgres
Group=postgres
EnvironmentFile=/etc/default/postgres_exporter
ExecStart=/opt/prometheus/exporters/postgres_exporter $FLAGS

SyslogIdentifier=postgres_exporter
Restart=always

[Install]
WantedBy=multi-user.target
```

/etc/default/postgres_exporter: 

```
DATA_SOURCE_NAME="user=postgres host=/var/run/postgresql/ sslmode=disable"
FLAGS="--auto-discover-databases --extend.query-path=/var/lib/postgresql/queries.yml"
```

/var/lib/postgresql/queries.yml: 

```
---
pg_replication:
  query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))::INT as lag"
  metrics:
    - lag:
        usage: "GAUGE"
        description: "Replication lag behind master in seconds"

pg_postmaster:
  query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
  metrics:
    - start_time_seconds:
        usage: "GAUGE"
        description: "Time at which postmaster started"

pg_stat_user_tables:
  query: "SELECT schemaname, relname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup, n_mod_since_analyze, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze, vacuum_count, autovacuum_count, analyze_count, autoanalyze_count FROM pg_stat_user_tables"
  metrics:
    - schemaname:
        usage: "LABEL"
        description: "Name of the schema that this table is in"
    - relname:
        usage: "LABEL"
        description: "Name of this table"
    - seq_scan:
        usage: "COUNTER"
        description: "Number of sequential scans initiated on this table"
    - seq_tup_read:
        usage: "COUNTER"
        description: "Number of live rows fetched by sequential scans"
    - idx_scan:
        usage: "COUNTER"
        description: "Number of index scans initiated on this table"
    - idx_tup_fetch:
        usage: "COUNTER"
        description: "Number of live rows fetched by index scans"
    - n_tup_ins:
        usage: "COUNTER"
        description: "Number of rows inserted"
    - n_tup_upd:
        usage: "COUNTER"
        description: "Number of rows updated"
    - n_tup_del:
        usage: "COUNTER"
        description: "Number of rows deleted"
    - n_tup_hot_upd:
        usage: "COUNTER"
        description: "Number of rows HOT updated (i.e., with no separate index update required)"
    - n_live_tup:
        usage: "GAUGE"
        description: "Estimated number of live rows"
    - n_dead_tup:
        usage: "GAUGE"
        description: "Estimated number of dead rows"
    - n_mod_since_analyze:
        usage: "GAUGE"
        description: "Estimated number of rows changed since last analyze"
    - last_vacuum:
        usage: "GAUGE"
        description: "Last time at which this table was manually vacuumed (not counting VACUUM FULL)"
    - last_autovacuum:
        usage: "GAUGE"
        description: "Last time at which this table was vacuumed by the autovacuum daemon"
    - last_analyze:
        usage: "GAUGE"
        description: "Last time at which this table was manually analyzed"
    - last_autoanalyze:
        usage: "GAUGE"
        description: "Last time at which this table was analyzed by the autovacuum daemon"
    - vacuum_count:
        usage: "COUNTER"
        description: "Number of times this table has been manually vacuumed (not counting VACUUM FULL)"
    - autovacuum_count:
        usage: "COUNTER"
        description: "Number of times this table has been vacuumed by the autovacuum daemon"
    - analyze_count:
        usage: "COUNTER"
        description: "Number of times this table has been manually analyzed"
    - autoanalyze_count:
        usage: "COUNTER"
        description: "Number of times this table has been analyzed by the autovacuum daemon"
```

OS: Ubuntu 18.04 LTS

Thanks.

**Comment by sfalkon** [comment]
Hello!

```
"user=postgres host=/var/run/postgresql/ sslmode=disable"
```

if you want to use --auto-discover-databases flag, you need to use URL-style:
```
"postgresql://postgres@:5432/postgres?host=/tmp/postgresql/&sslmode=disable"
```

**Comment by SergeSpinoza** [comment]
Hi. I try to do this. Then I have error on metrics page (http://host_ip:9187/metrics): 

```
An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric pg_replication_lag label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:nan >  was collected before with the same name and label values
* collected metric pg_postmaster_start_time_seconds label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:1.573809879e+09 >  was collected before with the same name and label values
```

> Hello!
> 
> ```
> "user=postgres host=/var/run/postgresql/ sslmode=disable"
> ```
> 
> if you want to use --auto-discover-databases flag, you need to use URL-style:
> 
> ```
> "postgresql://postgres@:5432/postgres?host=/var/run/postgresql/&sslmode=disable"
> ```

**Comment by sfalkon** [comment]
Hi!

If you use --auto-discover-databases flag, you don't to make queries which get the same data from different database in once instance. The metrics must to have unique sets of lable.
You can read about that in the article [habr](https://habr.com/ru/post/468573/) (Russian article)
It will fix in the next release.

> Hi. I try to do this. Then I have error on metrics page (http://host_ip:9187/metrics):
> 
> ```
> An error has occurred during metrics gathering:
> 
> 2 error(s) occurred:
> * collected metric pg_replication_lag label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:nan >  was collected before with the same name and label values
> * collected metric pg_postmaster_start_time_seconds label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:1.573809879e+09 >  was collected before with the same name and label values
> ```

**Comment by SergeSpinoza** [comment]
@sfalkon ok thanks. In version 0.8.0 it's works. 

What should the list of `exclude-databases` look like? `--exclude-databases=template0,template1` - it's right?

**Comment by sfalkon** [comment]
> @sfalkon ok thanks. In version 0.8.0 it's works.
> 
> What should the list of `exclude-databases` look like? `--exclude-databases=template0,template1` - it's right?

Yes, it's right. But you don't need to exclude templates from a list.  Database templates don't select from pg_database, when you used auto-discover-databases flag.

**Comment by IgorOhrimenko** [comment]
I have the same issue on the 0.8.0:
Run as:
`/opt/prometheus/exporters/postgres_exporter --extend.query-path=/var/lib/postgresql/queries.yml --auto-discover-databases`
`DATA_SOURCE_NAME="postgresql://postgres@:5432/postgres?host=/var/run/postgresql/&sslmode=disable"
`
At the endpoint I get:
`collected metric "pg_replication_lag" { label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:nan > } was collected before with the same name and label values`
and there are errors from other metrics.

**Comment by sfalkon** [comment]
> I have the same issue on the 0.8.0:
> Run as:
> `/opt/prometheus/exporters/postgres_exporter --extend.query-path=/var/lib/postgresql/queries.yml --auto-discover-databases`
> `DATA_SOURCE_NAME="postgresql://postgres@:5432/postgres?host=/var/run/postgresql/&sslmode=disable" `
> At the endpoint I get:
> `collected metric "pg_replication_lag" { label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:nan > } was collected before with the same name and label values`
> and there are errors from other metrics.

Can you show pg_replication section from your queries.yml

**Comment by IgorOhrimenko** [comment]
I am used old version queries.yaml, when I replaced with a new file the error was gone. Thanks.

**Comment by ImBug** [comment]
./postgres_exporter  --extend.query-path=q.yaml --config.file=config.yaml
----------------------------------------------------
ts=2023-11-10T06:35:58.785Z caller=proc.go:267 msg="Excluded databases" databases=[]
ts=2023-11-10T06:35:58.785Z caller=main.go:99 level=warn msg="The extended queries.yaml config is DEPRECATED" file=q.yaml
ts=2023-11-10T06:35:58.785Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="empty dsn"
ts=2023-11-10T06:35:58.789Z caller=tls_config.go:274 level=info msg="Listening on" address=0.0.0.0:9187
ts=2023-11-10T06:35:58.789Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=0.0.0.0:9187

--------------------------------------------------------
how to fix this problem "Failed to create PostgresCollector"

**Comment by sysadmind** [comment]
That is just a warning that you didn't set a DSN. In this case, the exporter will only scrape metrics via the /probe HTTP endpoint.

**Comment by ImBug** [comment]
Thank you,the DSN has bean setted,but the metrics dos not has any posrgresql metric.
------------------------------------------------------------------------------------------------------------
[root@localhost postgres]# ./postgres_exporter  --extend.query-path=q.yaml --config.file=config.yaml
ts=2023-11-14T01:12:48.837Z caller=proc.go:267 msg="Excluded databases" databases=[]
ts=2023-11-14T01:12:48.837Z caller=main.go:99 level=warn msg="The extended queries.yaml config is DEPRECATED" file=q.yaml
ts=2023-11-14T01:12:48.837Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="empty dsn"
ts=2023-11-14T01:12:48.841Z caller=tls_config.go:274 level=info msg="Listening on" address=0.0.0.0:9187
ts=2023-11-14T01:12:48.841Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=0.0.0.0:9187

why?

**Comment by sysadmind** [comment]
Logs still show that the DSN is not set. You can see where it says "empty dsn".
