### ISSUE TITLE
exporter version 0.7.0 is missing built-in pg_stat_bgwriter metric

### ISSUE THREAD

**Issue by findmyname666** [wrouesnel/postgres_exporter#336]
Hello everyone,

I installed `postgres-exporter` version `0.7.0` yesterday and I noticed that built-in metrics called `pg_stat_bgwriter` were removed in the following commit [34fdb69ee2170e122084e6d70aef91c0a1de22cc](https://github.com/wrouesnel/postgres_exporter/commit/34fdb69ee2170e122084e6d70aef91c0a1de22cc).
Was it removed on a purpose ?

P.S.: I hope that i was a mistake :P

**Comment by wrouesnel** [comment]
Huh...that shouldn't have been removed by that commit.
