### ISSUE TITLE
multi-host

### ISSUE THREAD

**Issue by dt-rush** [wrouesnel/postgres_exporter#344]
Running several `postgres_exporter` processes on multiple ports is a bit cumbersome to work around. 

**Why an issue on this repo?**
Specifying multiple hosts to monitor could be a more natural fit for an extension to the postgres_exporter process itself. 

**Precedent**
An exporter depending on async replies from sub-processes is not new, for example monitoring nodeJS's `cluster` workers[1], one defines a timeout in such a case.

[1] https://github.com/siimon/prom-client#usage-with-nodejss-cluster-module

**Comment by wrouesnel** [comment]
This was implemented.
