### ISSUE TITLE
Question: What are all the metrics that exporter provides

### ISSUE THREAD

**Issue by gowtham500** [wrouesnel/postgres_exporter#350]
Hello team,

Thanks for all the good work.  Can we get a list of metrics that this exporter provides.

**Comment by mbanck** [comment]
run `curl 127.0.0.1:9187/metrics | grep ^pg_` to get the Postgres-related ones (there are some internal metrics as well)

**Comment by wrouesnel** [comment]
The metrics provided by the exporter are committed on the assets branch - https://github.com/wrouesnel/postgres_exporter/tree/assets for each build.
