### ISSUE TITLE
Autodiscovery v0.8.0

### ISSUE THREAD

**Issue by dennybaa** [wrouesnel/postgres_exporter#351]
Hello,
I'm facing that auto discovery does not work properly.

As I understand with autodiscovery off I anyway get metrics for all of the database, so my catch is that  if a new database is created then no postgres exporter pod restart need.
  1.   Could you please clarify what is auto discovery for?

I have tried setting --disable-default-metrics --disable-settings-metrics --auto-discover-databases and the database to "", all this doesn't make the exporter work I still get errors (less though, but still) #314 

903 error(s) occurred:
* collected metric "pg_postmaster_start_time_seconds" { label:<name:"server" value:"postgres-stage-postgresql:5432" > gauge:<value:1.576833383e+09 > } was collected before with the same name and label values
* collected metric "pg_database_size" { label:<name:"datname" value:"postgres" > label:<name:"server" value:"postgres-stage-postgresql:5432" > gauge:<value:7.852703e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size" { label:<name:"datname" value:"identityservice" > label:<name:"server" value:"postgres-stage-postgresql:5432" > gauge:<value:8.532639e+06 > } was collected before with the same name and label values

**Comment by sfalkon** [comment]
Hi!

Maybe you use the old version queries.yaml. For some queries, you need to add field "master", Look into new file queries.yaml in the repository.

**Comment by dennybaa** [comment]
Thank you @sfalkon, this is a great catch. Seems to work  great https://github.com/helm/charts/pull/19749

**Comment by yashbhutwala** [comment]
@dennybaa can you close this?

**Comment by dennybaa** [comment]
@yashbhutwala Sure no problem
