### ISSUE TITLE
Docker `latest` tag does not have the same binary as `v0.8.0` - is this intentional?

### ISSUE THREAD

**Issue by unchris** [wrouesnel/postgres_exporter#369]
I've been using the `latest` tag for a docker-based setup of this exporter and noticed I was not getting the `pg_stat_bgwriter_*` stats which were re-introduced in `v0.8.0`. I changed my setup to pull `v0.8.0` instead and now I am getting the metrics.

Is the `latest` tag tracking a different branch or tag of the code? Or is it meant to be the same as (currently) `v0.8.0` and it's just a mistake? When I view on dockerhub it looks like the only thing that changed between the two was the hash of the `binary`, i.e., the binary for `postgres_exporter`.

Thanks!

**Comment by wrouesnel** [comment]
Yes this is intentional. "latest" is always the code on master when it builds and publishes. Tags are always published at versioned tags.
