### ISSUE TITLE
Documentation: Missing Part for just executing the binary

### ISSUE THREAD

**Issue by xFuture603** [wrouesnel/postgres_exporter#377]
Hi,

I've recently installed the postgres exporter and wondered why there is no documentation step for just executing the binary. The documentation reads to me as if I could either compile the code myself, or run it in a docker container. Is this desired, or is this kind of installation and executing simply missing in the documentation?

**Comment by wrouesnel** [comment]
Running the binary is well, just running the binary. It's a static go binary so how it's packaged and deployed is up to users/distributions/whatever.
