### ISSUE TITLE
pg_stat_replication* metrics missing

### ISSUE THREAD

**Issue by strzelecki-maciek** [wrouesnel/postgres_exporter#38]
Hi, 
this flag - config.expect-replication-stats is in README but its not supported anymore?

Im connecting postgres_exporter as superuser-enabled user to my 3 instances of psql (master-slave-slave, i use template1 as entrypoint db in the datasource), and i see many metrics, but the replication-oriented ones are missing.

Postgres version - 9.5.3 gets detected properly, and debug log level is not throwing any errors.

What am i doing wrong? Thanks!

**Comment by wrouesnel** [comment]
Ah that's actually an oversight on my part - the expect logic is not used at the moment.

Not sure why your replication metrics are missing. What are your debug logs showing?

**Comment by strzelecki-maciek** [comment]
```
root@jumbo ~ # export DATA_SOURCE_NAME="postgresql://aaa:bbb@10.10.0.40:5432/template1"
root@jumbo ~ # ./postgres_exporter -log.level debug
DEBU[0000] Querying Postgres Version                     source=postgres_exporter.go:931
INFO[0000] Semantic Version Changed: 0.0.0 -> 9.5.3      source=postgres_exporter.go:942
DEBU[0000] Querying SHOW variables                       source=postgres_exporter.go:778
DEBU[0000] Querying namespace:  pg_stat_database         source=postgres_exporter.go:911
DEBU[0000] Querying namespace:  pg_stat_database_conflicts  source=postgres_exporter.go:911
DEBU[0000] Querying namespace:  pg_locks                 source=postgres_exporter.go:911
DEBU[0000] Querying namespace:  pg_stat_replication      source=postgres_exporter.go:911
DEBU[0000] Querying namespace:  pg_stat_activity         source=postgres_exporter.go:911
DEBU[0000] Querying namespace:  pg_stat_bgwriter         source=postgres_exporter.go:911
INFO[0000] Starting Server: :9187                        source=postgres_exporter.go:1026
DEBU[0008] Querying Postgres Version                     source=postgres_exporter.go:931
DEBU[0008] Querying SHOW variables                       source=postgres_exporter.go:778
DEBU[0008] Querying namespace:  pg_stat_database_conflicts  source=postgres_exporter.go:911
DEBU[0008] Querying namespace:  pg_locks                 source=postgres_exporter.go:911
DEBU[0008] Querying namespace:  pg_stat_replication      source=postgres_exporter.go:911
DEBU[0008] Querying namespace:  pg_stat_activity         source=postgres_exporter.go:911
DEBU[0008] Querying namespace:  pg_stat_bgwriter         source=postgres_exporter.go:911
DEBU[0008] Querying namespace:  pg_stat_database         `source=postgres_exporter.go:911
```
There are no errors.
/metrics yields nothing with "replication"

And this psql master has two connected slaves

`pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_location | write_location | flush_location | replay_location | sync_priority | sync_state -------+----------+-------------+------------------+-------------+-----------------+-------------+-------------------------------+--------------+-----------+---------------+----------------+----------------+-----------------+---------------+------------ 12259 | 16392 | replication | walreceiver | 10.10.0.42 | | 38452 | 2016-11-27 11:12:20.205332+01 | | streaming | A0D/F017D2C0 | A0D/F017D2C0 | A0D/F017D2C0 | A0D/F017D248 | 0 | async 20415 | 16392 | replication | walreceiver | 10.10.0.41 | | 44108 | 2016-11-25 23:17:16.744832+01 | | streaming | A0D/F017D2C0 | A0D/F017D2C0 | A0D/F017D2C0 | A0D/F017D248 | 0 | async (2 rows)`

**Comment by dominikschulz** [comment]
Same problem here. Running PostgreSQL 9.5.4.

Anything else I could do to help debug this?

**Comment by wrouesnel** [comment]
Tagged version v0.1.1 (which will also publish as latest on docker) containing the fix for this bug. Thanks for the reports.

**Comment by syeda-saher73** [comment]
Hi

I'm still unable to view pg_stat_replication metrics 
Using version v0.4.5
I have tried with v0.1.1 which you have tagged still unable to get the metrics

**Comment by wrouesnel** [comment]
@syeda-saher73 could you post debug logs from your exporter?

**Comment by syeda-saher73** [comment]
Hi 

Any update on this issue?

**Comment by wrouesnel** [comment]
I've not been able to reproduce this issue locally so far, and we get metrics for replication in the tests.
