### ISSUE TITLE
master: true not working

### ISSUE THREAD

**Issue by kadaffy** [wrouesnel/postgres_exporter#380]
For a metric that should only run at the master database the option `master: true` does not avoid the execution on a standby server.

`postgres_exporter v0.8.0 (built with go1.11)`

Service running:

```
Main PID: 1877 (postgres_export)
    Tasks: 6 (limit: 6143)
   CGroup: /system.slice/postgres_exporter.service
           └─1877 /opt/prometheus/bin/postgres_exporter --extend.query-path=/etc/postgres_exporter/queries.yaml
```

logs on the standby server:

```
Mar 09 14:29:38 db002.host postgres_exporter[1877]: time="2020-03-09T14:29:38Z" level=info msg="Error running query on database \"localhost:5432\": pg_backups_info pq: cannot execute CREATE TABLE in a read-only transaction" source="postgres_exporter.go:1356"
Mar 09 14:29:38 db002.host postgres_exporter[1877]: time="2020-03-09T14:29:38Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:878"
Mar 09 14:29:38 db002.host postgres_exporter[1877]: time="2020-03-09T14:29:38Z" level=info msg="Semantic Version Changed on \"localhost:5432\": 0.0.0 -> 9.6.12" source="postgres_exporter.go:1405"
```

the metric definition is with the option `master: true`

**Comment by sfalkon** [comment]
Can you show your metric or queries file?

**Comment by kadaffy** [comment]
sure, this is the metric in the queries.yaml 

```
pg_backups_info:
  query: |
    with stanza as (
    select data->'name' as name,
           data->'backup'->(
               jsonb_array_length(data->'backup') - 1) as last_backup,
           data->'archive'->(
               jsonb_array_length(data->'archive') - 1) as current_archive
      from jsonb_array_elements(postgres_exporter.pgbackrest_info()) as data
    )
    select name,
    extract (epoch from now() - to_timestamp((last_backup->'timestamp'->>'stop')::numeric)) as sec_since_last_successful_backup
    from stanza;
  master: true
  metrics:
    - name:
        usage: "LABEL"
        description: "pgBackRest stanza name"
    - sec_since_last_successful_backup:
        usage: "GAUGE"
        description: "Number of seconds since last successful backup"
```

**Comment by sfalkon** [comment]
You have a problem with function pgbackrest_info().

Execute \df+ postgres_exporter.pgbackrest_info() and look at to column "Source code". You will see "... create temp table ..." it will not work on standby or read-only transactions.

**Comment by kadaffy** [comment]
I already know that `create temp table` does not work on a standby server the question is why the `master: true` option does no avoid the execution on a standby server? What is the real function of `master: true`?

**Comment by sfalkon** [comment]
It is not the role of a cluster. It is the role of a database when autodiscovery is enabled.
If you will be to get metrics from pg_stat_activity and will not be used master: true. You will get duplicate metrics and errors.
If metric to have the option "master: true" it executes at the only database set in DSN

**Comment by kadaffy** [comment]
Great, thanks for the explanation. I'll proceed to close the issue.
