### ISSUE TITLE
Publish docker image on Docker Hub

### ISSUE THREAD

**Issue by keegancsmith** [wrouesnel/postgres_exporter#4]
I see you have a Dockerfile, but no corresponding image on dockerhub. Would be cool if you could publish an image. Currently I am just publishing an image to a private image repo, but would just use the public one if it existed.

**Comment by wrouesnel** [comment]
The Dockerfile at the moment is broken. I need to tweak the way it works so it's a true minimal image.

On 11 March 2016 5:32:43 PM AEDT, Keegan Carruthers-Smith <notifications@github.com> wrote:
>I see you have a Dockerfile, but no corresponding image on dockerhub.
>Would be cool if you could publish an image. Currently I am just
>publishing an image to a private image repo, but would just use the
>public one if it existed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wrouesnel/postgres_exporter/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by keegancsmith** [comment]
I'm using something like this (where image and tag are specified to internal conventions we use)

```
FROM alpine:3.2

ADD .bin/postgres_exporter /usr/bin/
EXPOSE 9113
ENTRYPOINT ["/usr/bin/postgres_exporter"]
```

```
.PHONY: docker

docker: .bin/postgres_exporter
        docker build -t $(image):$(tag) $@

.bin/postgres_exporter: postgres_exporter.go
        @mkdir .bin
        GOARCH=amd64 GOOS=linux go build -o .bin/postgres_exporter postgres_exporter.go
```

BTW thanks for the exporter!

**Comment by wrouesnel** [comment]
Happy to have resolved this now - you can acquire my "official" image with `docker pull wrouesnel/postgres_exporter` or build your own with `make docker` from the repository now.

**Comment by keegancsmith** [comment]
Thanks!
