### ISSUE TITLE
-config.expect-replication-stats doesn't actually work

### ISSUE THREAD

**Issue by ahanselka** [wrouesnel/postgres_exporter#41]
We are attempting to [enable replication stats](https://gitlab.com/gitlab-com/infrastructure/issues/782#note_19092032) in the most recent version of the exporter, but it says that the config flag is not defined. Below is the output of the command and the command we are running. I've tried it with and without `true` attached to the config option.

/etc/sv/postgres_exporter/run:
```
root@db1:~# cat /etc/sv/postgres_exporter/run
#!/bin/sh

export DATA_SOURCE_NAME="<redacted>"
exec chpst -u prometheus /opt/prometheus/postgres_exporter/postgres_exporter -config.expect-replication-stats=true
```

```
root@db1:~# /etc/sv/postgres_exporter/run
flag provided but not defined: -config.expect-replication-stats
Usage of /opt/prometheus/postgres_exporter/postgres_exporter:
  -dumpmaps
        Do not run, simply dump the maps.
  -extend.query-path string
        Path to custom queries to run.
  -log.format value
        If set use a syslog logger or JSON logging. Example: logger:syslog?appname=bob&local=7 or logger:stdout?json=true. Defaults to stderr.
  -log.level value
        Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal].
  -web.listen-address string
        Address to listen on for web interface and telemetry. (default ":9187")
  -web.telemetry-path string
        Path under which to expose metrics. (default "/metrics")
```

**Comment by wrouesnel** [comment]
Sorry about this - I added the line to the README.md when looking at fixing a different problem (detecting if replication was broken) but ultimately found it wasn't needed.

Replication stats was broken in the previous release and fixed just yesterday. Please upgrade to v0.1.1 which contains the fix: https://github.com/wrouesnel/postgres_exporter/releases/download/v0.1.1/postgres_exporter

**Comment by pcarranza** [comment]
Thanks @wrouesnel !
