### ISSUE TITLE
extended queries added but not visible in /metrics

### ISSUE THREAD

**Issue by bgroupe** [wrouesnel/postgres_exporter#438]
Hi. I have the following simple query: 

~~~yaml
    pg_oban_jobs:
      query: select count(*) from oban_jobs where state = 'discarded';
      master: true
      metrics:
        - count:
            usage: "GUAGE"
            description: "Number of discarded oban jobs"
~~~

With debug logs on, when I start up the exporter I see the following:

~~~
time="2020-09-24T17:37:51Z" level=debug msg="New user metric namespace from YAML: pg_oban_jobs Will cache results for: 0" source="postgres_exporter.go:502"
time="2020-09-24T17:37:51Z" level=debug msg="Adding new metric pg_oban_jobs from user YAML file." source="postgres_exporter.go:556"
time="2020-09-24T17:37:51Z" level=debug msg="Adding new query override pg_oban_jobs from user YAML file." source="postgres_exporter.go:567"
~~~

And when I hit `/metrics` I see the following:

~~~
time="2020-09-24T17:38:40Z" level=debug msg="Querying namespace:  pg_oban_jobs" source="postgres_exporter.go:1323"
~~~

However I do not see my metric anywhere in the metrics output. Am I misunderstanding something?

**Comment by cjchang1688** [comment]
try adding "as count" in the query
`select count(*) as count from oban_jobs where state = 'discarded';`

**Comment by bgroupe** [comment]
@cjchang1688 Thanks I forgot to mention I tried that, it still doesn't work. 

I am using the latest docker image, version is: 

`postgres_exporter v0.8.0-9-gb12c8ab (built with go1.11)`

**Comment by frenkye** [comment]
Are you accounting for fact, the exporter should connect to database `postgres`?

1) Is the table `oban_jobs` in that database?
2) Do your user for exporter have access to the schema?

I would start connecting exactly as your mon user and try run this query.

**Comment by kadaffy** [comment]
You have a typo  in your definition:

```
- count:
            usage: "GUAGE"
```

The correct word is `GAUGE`.

**Comment by bgroupe** [comment]
@kadaffy 🤦  

works now, thank you.
