### ISSUE TITLE
WARN[1167] PostgreSQL version is lower on "xxxx" then our lowest supported version! Got 8.3.23 minimum supported is 9.1.0.  source="postgres_exporter.go:1400"

### ISSUE THREAD

**Issue by liuzjccc** [wrouesnel/postgres_exporter#446]
What is the minimum supported version of posgresql? My version is 8.3.23.

**Comment by liuzjccc** [comment]
When using the package such an error：pg_stat_user_tables pq: column "n_mod_since_analyze" does not exist

**Comment by wrouesnel** [comment]
The error is as it says - it's too difficult to support very low versions of Postgres (docker containers are also not readily available) so the decision was made to start at 9.1
