### ISSUE TITLE
Error scanning version string: on Postgres 9.5

### ISSUE THREAD

**Issue by phuqm** [wrouesnel/postgres_exporter#45]
Getting the following error:

"Proceeding with outdated query maps, as the Postgres version could not be determined: Error scanning version string: pq: SSL is not enabled on the server."

Server is 9.5.   This happens whether connecting locally ( as user postgres ) or remotely (also as a superuser).   It is true that SSL is not enabled. 

pg_exporter_last_scrape_error 1

Let me know if you need further information from me.

**Comment by wrouesnel** [comment]
How are you launching the v exporter?

**Comment by phuqm** [comment]
Thanks for the response....

Last time it was run:
/usr/local/sbin/postgres_exporter -extend.query-path /etc/extenders/queries.yaml -log.level debug
Though the same thing happens without the extend.query-path or log.level.
DATA_SOURCE_NAME="postgres://localhost/"   (run as local "postgers" user)
Though same thing happens when using a remote connection.   (maybe I should make the binary again and see if there was any errors I overlooked :/)
Finally, I should have probably mentioned that this is on CentOS7

**Comment by wrouesnel** [comment]
The postgres library defaults to using SSL.

From the quick start section theres an example of using it without SSL.

Change your data source variable to read:

`postgres://localhost:5432/?sslmode=disable`

**Comment by phuqm** [comment]
All looks good:

# make
go vet .
go test -v -cover .
=== RUN   Test
OK: 1 passed
--- PASS: Test (0.00s)
PASS
coverage: 5.2% of statements
ok      postgres_exporter       0.007s
CGO_ENABLED=0 go build -a -ldflags "-extldflags '-static' -X main.Version=v0.1.1-3-g2c6594e" -o postgres_exporter .

**Comment by phuqm** [comment]
excellent.   Will try, thanks a lot.  Sorry for the not-bug :/

**Comment by phuqm** [comment]
Works great. tnx again for the help, and tnx for the exporter.
