### ISSUE TITLE
Metric was collected before with the same name and label values - pg_database_size_bytes

### ISSUE THREAD

**Issue by CoolCold** [wrouesnel/postgres_exporter#451]
# Description
collecting database sizes with pg_database_size_bytes ( https://github.com/wrouesnel/postgres_exporter/blob/b12c8ab04e077ba493b5b490f8733b8a44e0ef22/queries.yaml#L124 ) and having the issue when removing setting of `master: true`.

# Problem
```
An error has occurred while serving metrics:

4 error(s) occurred:
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"postgres" > label:<name:"server" value:"localhost:5432" > gauge:<value:8.180383e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"template1" > label:<name:"server" value:"localhost:5432" > gauge:<value:8.012291e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"template0" > label:<name:"server" value:"localhost:5432" > gauge:<value:8.155807e+06 > } was collected before with the same name and label values
* collected metric "pg_database_size_bytes" { label:<name:"datname" value:"pgbench" > label:<name:"server" value:"localhost:5432" > gauge:<value:4.78909087e+08 > } was collected before with the same name and label values

```
# Information
 As I could understand from sources ( https://github.com/wrouesnel/postgres_exporter/blob/b12c8ab04e077ba493b5b490f8733b8a44e0ef22/cmd/postgres_exporter/postgres_exporter.go#L116 ):

```
type UserQuery struct {
	Query        string    `yaml:"query"`
	Metrics      []Mapping `yaml:"metrics"`
	Master       bool      `yaml:"master"`        // Querying only for master database
	CacheSeconds uint64    `yaml:"cache_seconds"` // Number of seconds to cache the namespace result metrics for.
}
```
this setting influence a logical switch to indicate that instance is a master server. How such stats gathering should be configured on slave server then? From SQL point of view, executing query works both on master/slave servers, so I don't understand the difference here and why that switch is important.

version:
```
[ec2-user@ip-172-31-12-46 postgres_exporter]$ ./postgres_exporter --version
postgres_exporter v0.8.0-9-gb12c8ab (built with go1.13.15)
```

**Comment by wrouesnel** [comment]
As it says: the labels aren't different. Somehow it looks like you're querying the same "host" value on all machines.

`master` doesn't refer to a master server, it refers to the database the exporter initially connects to on a particular DB server. This comes into play for "global" postgres metrics (since you can't connect and not specify some DB with the underlying library).

**Comment by CoolCold** [comment]
I will comment on that for future uses as I understand the issue myself:

**master** refers to single object:
* for example global statistics for replication or recovery mode -it's global per server instance, not per database
* compare this to "per database" values like database size, queries for that database and so on. 

So if you have auto discovery turned on, you need to specify "master" for that queries which should not be executed against every discovered database (something global), which is exactly my case here.
query:
```
query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
```
should not be repeated for every discovered DB.

**Comment by CoolCold** [comment]
> 
> 
> As it says: the labels aren't different. Somehow it looks like you're querying the same "host" value on all machines.
> 
> `master` doesn't refer to a master server, it refers to the database the exporter initially connects to on a particular DB server. This comes into play for "global" postgres metrics (since you can't connect and not specify some DB with the underlying library).

Thanks for explanation (this should be in docs I believe), I got the same impression by my experience.
