### ISSUE TITLE
queryNamespaceMappings returned 1 errors

### ISSUE THREAD

**Issue by ZihangYin-Compass** [wrouesnel/postgres_exporter#458]
I am using the docker image here https://hub.docker.com/r/wrouesnel/postgres_exporter/tags

When running following SQLs 
SELECT tablename, iname, ROUND((CASE WHEN otta=0 THEN 0.0 ELSE sml.relpages::FLOAT/otta END)::NUMERIC,1) AS tbloat,
             CASE WHEN relpages < otta THEN 0 ELSE bs*(sml.relpages-otta)::BIGINT END AS wastedbytes,
             ROUND((CASE WHEN iotta=0 OR ipages=0 THEN 0.0 ELSE ipages::FLOAT/iotta END)::NUMERIC,1) AS ibloat,
             CASE WHEN ipages < iotta THEN 0 ELSE bs*(ipages-iotta) END AS wastedibytes FROM (SELECT 
             tablename, cc.reltuples, cc.relpages, bs, CEIL((cc.reltuples*((datahdr+ma-
             (CASE WHEN datahdr%ma=0 THEN ma ELSE datahdr%ma END))+nullhdr2+4))/(bs-20::FLOAT)) AS otta,
             COALESCE(c2.relname,'?') AS iname, COALESCE(c2.reltuples,0) AS ituples, COALESCE(c2.relpages,0) AS ipages,
             COALESCE(CEIL((c2.reltuples*(datahdr-12))/(bs-20::FLOAT)),0) AS iotta -- very rough approximation, assumes all cols
             FROM (SELECT ma,bs,tablename, (datawidth+(hdr+ma-(CASE WHEN hdr%ma=0 THEN ma ELSE hdr%ma END)))::NUMERIC AS datahdr,
             (maxfracsum*(nullhdr+ma-(CASE WHEN nullhdr%ma=0 THEN ma ELSE nullhdr%ma END))) AS nullhdr2 FROM (SELECT tablename, hdr, ma, bs,
             SUM((1-null_frac)*avg_width) AS datawidth, MAX(null_frac) AS maxfracsum, hdr+(SELECT 1+COUNT(*)/8 FROM pg_stats s2
             WHERE null_frac<>0 AND s2.tablename = s.tablename) AS nullhdr FROM pg_stats s, (SELECT(SELECT current_setting('block_size')::NUMERIC) AS bs,
             CASE WHEN SUBSTRING(v,12,3) IN ('8.0','8.1','8.2') THEN 27 ELSE 23 END AS hdr, CASE WHEN v ~ 'mingw32' THEN 8 ELSE 4 END AS ma 
             FROM (SELECT version() AS v) AS foo) AS constants WHERE current_database() = 'listings_production' and schemaname = 'public' GROUP BY 1,2,3,4) AS foo
             ) AS rs JOIN pg_class cc ON cc.relname = rs.tablename JOIN pg_namespace nn ON cc.relnamespace = nn.oid AND nn.nspname = 'public' 
             LEFT JOIN pg_index i ON indrelid = cc.oid LEFT JOIN pg_class c2 ON c2.oid = i.indexrelid) AS sml

I got the error 
level=info msg="Error running query on database \"messier-staging-aurora-cluster-writer-backup.cj5ubinouelt.us-east-1.rds.amazonaws.com:5432\": pg_bloat pq: syntax error at end of input" 

However, I ran the above SQL in PGAdmin, the SQL itself is good.

**Comment by wrouesnel** [comment]
Looks like your queries.yml file isn't formatted properly.
