### ISSUE TITLE
dollar sign in password

### ISSUE THREAD

**Issue by xtreme-uz** [wrouesnel/postgres_exporter#459]
the dollar sign in the password is copied to the docker container with a change.
example:
env: DATA_SOURCE_NAME="postgresql://postgres:De$kt0p@2019@myhost:5432/spclients?sslmode=disable"
container env: DATA_SOURCE_NAME=postgresql://postgres:De@2019@myhost:5432/spclients?sslmode=disable

**Comment by wrouesnel** [comment]
Without more info I'm not sure this is an error with pg - looks like a shell escaping error - "$kt0p" is being interpreted as a bash environment variable substitution.
