### ISSUE TITLE
WARN[0000] Postgres version could not be determined

### ISSUE THREAD

**Issue by shirwa** [wrouesnel/postgres_exporter#46]
Hi,

I'm using latest postgresql 9.4 release (9.4.10) on CentOS 7.3. When i run postgres_exporter, i'm getting following error:

"WARN[0000] Postgres version could not be determined. Proceeding with outdated query maps.  source=postgres_exporter.go:987".

**Comment by shirwa** [comment]
Not getting the error on postgresql version 9.4.9. Could be parsing error when there is two digits after major version (9.4.xx).

**Comment by wrouesnel** [comment]
This is the version regex : `^\w+ (\d+\.\d+\.\d+)`

So it would match correctly. I'm wondering if the semver library I'm using handles double digits correctly. I'll cook up a new test when I'm back more regularly at my PC.

**Comment by saifulmuhajir** [comment]
This also happened on Ubuntu 16.04 with PostgreSQL 9.5.6. So, I guess this has nothing to do with double digits(?)

**Comment by saifulmuhajir** [comment]
This happened on my friend's computer and apparently when checking manually the DATA_SOURCE_NAME parameter, the user specified is not permitted to login. 

Maybe the exporter assumed error logon status, which is text, as postgres version and the error fired.

**Comment by wrouesnel** [comment]
The specific error will fire if the connection fails (and is valid - there's no way for the exporter to determine the version, but if the account is created later then it will update it's maps).

Closing this issue unless a specific bug is found.
