### ISSUE TITLE
pg_replication_.* metrics not found

### ISSUE THREAD

**Issue by dusatvoj** [wrouesnel/postgres_exporter#464]
I've found [this awesome alerts guide](https://awesome-prometheus-alerts.grep.to/rules.html) but I don't have any `pg_replication_.*`

Can you tell me what are prerequisities?

Postgresql version: `postgresql-12/focal-updates,focal-security,now 12.5-0ubuntu0.20.04.1 amd64 [installed,upgradable to: 12.5-1.pgdg20.04+1]` with `postgresql-12-repmgr/now 5.0.0-4.pgdg20.04+1 amd64 [installed,upgradable to: 5.2.0-1.pgdg20.04+1]` 
Exporter: `prometheus-postgres-exporter/focal,now 0.8.0+ds-1 amd64 [installed]`

Thank you

**Comment by kadaffy** [comment]
@dusatvoj this is a custom query you need to add via configuration using `extend.query-path` and a `queries.yaml` file, the metric I use is this: 

```
pg_replication:
  master: true
  query: |
    SELECT
    CASE
    WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
    ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp())::INTEGER
    END
    AS lag,
    CASE WHEN pg_is_in_recovery() THEN 1 ELSE 0 END as is_replica;
  metrics:
    - lag:
        usage: "GAUGE"
        description: "Replication lag behind master in seconds"
    - is_replica:
        usage: "GAUGE"
        description: "Indicates if this host is a replica"
```

**Comment by dusatvoj** [comment]
@kadaffy didn't knew that ... thank you

**Comment by radosevic** [comment]
> @dusatvoj this is a custom query you need to add via configuration using `extend.query-path` and a `queries.yaml` file, the metric I use is this:
> 
> ```
> pg_replication:
>   master: true
>   query: |
>     SELECT
>     CASE
>     WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0
>     ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp())::INTEGER
>     END
>     AS lag,
>     CASE WHEN pg_is_in_recovery() THEN 1 ELSE 0 END as is_replica;
>   metrics:
>     - lag:
>         usage: "GAUGE"
>         description: "Replication lag behind master in seconds"
>     - is_replica:
>         usage: "GAUGE"
>         description: "Indicates if this host is a replica"
> ```

If you need this metric for PostgreSQL  < = 9.5.x you have to use this:

`pg_replication:
  master: true
  query: |
    SELECT
    CASE
    WHEN pg_last_xlog_receive_location() = pg_last_xlog_replay_location() THEN 0
    ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp())::INTEGER
    END
    AS lag,
    CASE WHEN pg_is_in_recovery() THEN 1 ELSE 0 END as is_replica;
  metrics:
    - lag:
        usage: "GAUGE"
        description: "Replication lag behind master in seconds"
    - is_replica:
        usage: "GAUGE"
        description: "Indicates if this host is a replica"`
