### ISSUE TITLE
pq: function pg_current_wal_lsn() does not exist when using pg 9.6.20

### ISSUE THREAD

**Issue by zealot0515** [wrouesnel/postgres_exporter#467]
Hi, I use postgres_exporter to pull metrics, 
but I got error like below...
```
time="2021-01-04T07:51:23Z" level=info msg="Established new database connection to \"__POSTGRES_9_6_20__\"." source="postgres_exporter.go:898"
time="2021-01-04T07:51:23Z" level=info msg="Semantic Version Changed on \"__POSTGRES_9_6_20__\": 0.0.0 -> 9.6.20" source="postgres_exporter.go:1425"
time="2021-01-04T07:51:24Z" level=info msg="Error running query on database \"__POSTGRES_9_6_20__\": pg_replication_slots pq: function pg_current_wal_lsn() does not exist" source="postgres_exporter.go:1376"
time="2021-01-04T07:51:24Z" level=error msg="queryNamespaceMappings returned 1 errors" source="postgres_exporter.go:1494"
```
i saw these code block in postgres_exporter.go, can i skip this metrics? 
![image](https://user-images.githubusercontent.com/45503385/103521000-03839680-4eb3-11eb-932d-6e732078213b.png)

**Comment by rezart** [comment]
@zealot0515 what was your solution to this? I am running into the same issue with pg 9.6

**Comment by jiang-wei** [comment]
This function is only available in PG 10
I think you can just set  the version to ">=10.0.0"

**Comment by zealot0515** [comment]
> @zealot0515 what was your solution to this? I am running into the same issue with pg 9.6

i rollback to use version 0.8.0
you can try this docker image, 

wrouesnel/postgres_exporter:v0.8.0
