### ISSUE TITLE
Custom query may cause "integer out of range" errors

### ISSUE THREAD

**Issue by zstyblik** [wrouesnel/postgres_exporter#49]
Hello,

I've used `queries.yaml` from the repository itself. However, it seems that our shared buffers are too big and are causing "integer out of range".

```
postgres_exporter[8248]: time="2017-02-09T10:21:36Z" level=info
msg="Error running query on database:  pg_settings_shared_buffers pq: integer out of range\n"
source="postgres_exporter.go:919"
```

I'm wondering whether this is bug or feature.

Thank you very much.

**Comment by wrouesnel** [comment]
I'll have to check in where this is being kicked up from. It may be a SQL.Wrapper problem, but in principle we should be collecting ints as large as 2^54 just fine...

**Comment by sdif** [comment]
Hi, personally I changed the cast from int to bigint in [queries.yaml](https://github.com/wrouesnel/postgres_exporter/blob/master/queries.yaml#L16) and it solved the problem

**Comment by wrouesnel** [comment]
Hm I'm thinking "int" must be 32-bit, which would explain it. `bigint` isn't quite right since what we actually want (ideally) is a float64.

**Comment by gregscds** [comment]
Converting to bigint is the correct PostgreSQL cast for the number of bytes in shared_buffers.  On the Go side I'd expect that to then become an int64.  It's not possible for this number you're computing to exceed a 64 bit integer size.  The shared buffer allocation code in the database does a similar computation which would then break, and this number is gigantic compared to any reachable memory size.

Using a regular 32 bit int for this and database sizes are both common errors for monitoring code people write.  Once those turn to 64 bits wide you're good.  I'd expect that using a float instead would introduce casting headaches for people trying to consume this number down the line.

**Comment by wrouesnel** [comment]
Prometheus only deals in float64's - on the Golang side we're using those everywhere (with int64 from the SQL wrapper).

Closing this issue as resolved.
