### ISSUE TITLE
Display query in error message

### ISSUE THREAD

**Issue by tgxworld** [wrouesnel/postgres_exporter#55]
```
time="2017-02-27T02:15:20Z" level=info msg="Error running query on database:  pg_stat_replication pq: recovery is in progress\n" source="postgres_exporter.go:919"
```

I'm getting a generic error message about an error when running a query on the database. However, it is difficult for me to track down which query/custom query is causing this issue. It'll be really helpful if the error message could display the query that has been ran. 

Thanks in advanced :+1:

**Comment by wrouesnel** [comment]
Related to #52

**Comment by mpalmer** [comment]
It does seem plausible that this is related to #52; do you have any plans to release a new version which logs the query at issue in the near future, so we can confirm whether that is the case?

**Comment by wrouesnel** [comment]
Ah yes. This one slipped through amidst the big pg_settings change. Shouldn't be too hard to fix.
