### ISSUE TITLE
Logging connection string exposes credentials

### ISSUE THREAD

**Issue by alkar** [wrouesnel/postgres_exporter#57]
When a DB connection cannot be established, https://github.com/wrouesnel/postgres_exporter/blob/master/postgres_exporter.go#L999 will log the connection string which includes username & password.

I'm not sure if there's any true value in logging that at all but if you want to log the connection string it'd be best to either mask the password or perhaps use `url.Parse()` and just log the extracted `Host`?

Happy to raise a PR for this. Thoughts?

**Comment by wrouesnel** [comment]
I think I explicitly recall doing this because we had some problem where it eventually turned out to be the password.

But yeah, there's no good reason to do it - if you want to raise a PR I'll accept - definitely my preference is parse and mask.

**Comment by alkar** [comment]
@wrouesnel thanks for the response. I've raised #58 so we can take the discussion there?

**Comment by wrouesnel** [comment]
Resolved by 12b95c44d41f56a503ac391de65fa87e89697396
