### ISSUE TITLE
Provide alerts example

### ISSUE THREAD

**Issue by gianrubio** [wrouesnel/postgres_exporter#68]
I can't found examples on how to monitor this metrics, it'll be useful if this project provide some examples.

For now I'm just using one alert to check if the max connections is 80% > max connections. 

```
    ALERT PostgresqlHighMaxConnections
      IF sum(pg_runtime_variable_max_connections * 0.8) -  sum(pg_stat_activity_count) == 0 OR absent(pg_runtime_variable_max_connections)
      FOR 2m
      LABELS {
        service = "postgresql",
        severity = "critical",
      }
      ANNOTATIONS {
        summary = "Connections is too high",
        description = "Postgresql reachs 80% of the max connections",
      }
```

@wrouesnel Is here the right place to ask for contributions?

**Comment by wrouesnel** [comment]
Absolutely.

Should be some general best practice knowledge we can make part of the repo out there.

**Comment by bchanan03** [comment]
https://github.com/wrouesnel/postgres_exporter/issues/130

**Comment by wrouesnel** [comment]
Flagging as an enhancement, but Prometheus 2's syntax has changed substantially.
