### ISSUE TITLE
Help with permissions

### ISSUE THREAD

**Issue by MCPDanilovich** [wrouesnel/postgres_exporter#69]
Hello,
I wont create additional user for collect metricks in postgress. Which permissions i should have in postgres for postgres_exporter?

**Comment by saifulmuhajir** [comment]
Any role with superuser privileges would do just fine. Such as postgres
itself or if you have RDS, any role granted with rds_superuser.

**Comment by wrouesnel** [comment]
Closing this if no further changes needed.
