### ISSUE TITLE
Multiple servers in DATA_SOURCE_NAME

### ISSUE THREAD

**Issue by andel7** [wrouesnel/postgres_exporter#72]
Is it possible to provide several different PG servers in environment variable ?
Or I have to setup exporter per DB ?

**Comment by uspen** [comment]
> Or I have to setup exporter per DB ?
Yes, I do it like that

**Comment by macnibblet** [comment]
This is what I use for the MySQL exporter i'm also using and it should work the same for postgres
`user:password@tcp(host:port)/` 

If you don't wrap it with the tcp statement it get confused and returns a weird error.

**Comment by macnibblet** [comment]
Actually, I just tried it, and it does not work, it will try and connect to the same database as the username. But a funny thing is that regardless of which database to connect to it will get stats for all the databases.

**Comment by eonarts** [comment]
I'm using RDS postgres and I'm using it with Percona's PMM which is MySQL and MongoDB. I put the postgres_exporter with the mysql & mongo exporters.  I created 2 files in /etc/systemd/system, one for the master, one for the replica. They each have a different port and it is in the range of the PMM ports which start with 42000.  Mysql & Mongo are using some of those ports so I did the following:
Master 
ExecStart=/bin/sh -c '/usr/local/percona/pmm-client/postgres_exporter -extend.query-path /etc/postgres_exporter/queries.yml -web.listen-address=##.##.##.##:42201  >> /var/log/pmm-postgres-metrics-42201.log  2>&1'

Replica
/etc/postgres_exporter/queries.yml -web.listen-address=##.##.##.##:42202  >> /var/log/pmm-postgres-metrics-42202.log  2>&1'

There are more lines in the files but these are the important ones!

Now I have to figure out how to get the graph to recognize each of them separately!

**Comment by wrouesnel** [comment]
`instance` in Prometheus will identify the exporters, and you can add custom labels.

Currently the exporter works like the MySQL exporter and is 1 DB per exporter. Theoretically this could be changed, but it would be a fair bit of work at this point to verify nothing gets cross-contaminated in the refactor so it's not planned.
