### ISSUE TITLE
error during postgres upgrade

### ISSUE THREAD

**Issue by otsuarez** [wrouesnel/postgres_exporter#75]
Hi,
We're using postgres_exporter to monitor our server which is currently running 9.3.
An attempt to upgrade it to 9.6, using pg_upgrade failed with the following error:
```
pg_restore: creating VIEW "postgres_exporter.pg_stat_activity"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 175; 1259 1807049 VIEW pg_stat_activity postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  column reference "query" is ambiguous
LINE 29:     "f_select_pg_stat_activity"."query"
```

It was a in-place pg_upgrade on the same server, running Ubuntu 16.04 using postgresql packages from postgresql.org repository. 
Not directly related to the exporter working, which had been working great but still someone might had faced this issue at some point.

Any idea what could had triggered that error?

**Comment by wrouesnel** [comment]
This doesn't look like it's related to the exporter at all (as it wouldn't have been able to scrape during the upgrade). Try the offical Postgres mailing lists and other support channels - it's outside the scope of this project.

**Comment by mydimension** [comment]
we ran into this ourselves. it is related to the guidance given the README to create 2 views for use by non-superusers. the presence of these views causes problems when a postgres upgrade changes the structure of the system views: the user views now refer to an invalid structure will block the upgrade with this very message. our system complained about the `activity` column in a 9.2 to 9.6 upgrade

**Comment by trnubo** [comment]
I've hit the same issue while performing a 9.6 to 12 upgrade. As @mydimension said the error is related to the views from the guidance in the README.

```
pg_restore: creating VIEW "postgres_exporter.pg_stat_replication"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 189; 1259 16400 VIEW pg_stat_replication postgres
pg_restore: error: could not execute query: ERROR:  column reference "sync_priority" is ambiguous
LINE 28:     "get_pg_stat_replication"."sync_priority",
             ^
```

Dropping the view `DROP VIEW postgres_exporter.pg_stat_replication;` and recreating it post upgrade worked around the issue.

**Comment by imp1sh** [comment]
This issue is not invalid. We also had to workaround this problem when we upgraded from Postgresql 10 to 13.
```
ERROR: column reference "backend_type" is ambiguous LINE 33: "get_pg_stat_activity"."backend_type"
pg_restore: error: could not execute query: ERROR: column reference "backend_type" is ambiguous
LINE 33: "get_pg_stat_activity"."backend_type"
```
It cost us quite a lot of manpower to find the solution of this problem since googling did not lead to this *closed* issue.

**Comment by richzw** [comment]
> I've hit the same issue while performing a 9.6 to 12 upgrade. As [@mydimension](https://github.com/mydimension) said the error is related to the views from the guidance in the README.
> 
> ```
> pg_restore: creating VIEW "postgres_exporter.pg_stat_replication"
> pg_restore: while PROCESSING TOC:
> pg_restore: from TOC entry 189; 1259 16400 VIEW pg_stat_replication postgres
> pg_restore: error: could not execute query: ERROR:  column reference "sync_priority" is ambiguous
> LINE 28:     "get_pg_stat_replication"."sync_priority",
>              ^
> ```
> 
> Dropping the view `DROP VIEW postgres_exporter.pg_stat_replication;` and recreating it post upgrade worked around the issue.

Same work around on my side. Drop view before upgrading and recreating it after PG upgrading.
