### ISSUE TITLE
feature request: up metric ?

### ISSUE THREAD

**Issue by zerthimon** [wrouesnel/postgres_exporter#84]
It would be convenient to have postgres exporter provide 'up' metric.
Just like most other popular exporters do (mysql, redis, etc)

The idea of this metric is that it outputs the value of 1 when there is a connection to postgres and 0 when there is no connection.

Having this metric one could set up an alert on postgres unavailability.
Here is the example from mysql:

```
# Mysql service not up
ALERT MysqlUp
  IF mysql_up{job = "mysql"} != 1
  FOR 1m
....
...
```

**Comment by zerthimon** [comment]
Does anyone have an idea for a rule to alert when postgres goes down ?

**Comment by wrouesnel** [comment]
Oh, I thought I replied to this - you need to look at `pg_exporter_last_scrape_error` which will be 1 when scrape's are failing. It's not reliable for "service down" but a properly working exporter should successfully return a scrape with no error.

**Comment by zerthimon** [comment]
@wrouesnel thanks, that should be enough for a while.
