### ISSUE TITLE
tar.gz releases 

### ISSUE THREAD

**Issue by c4milo** [wrouesnel/postgres_exporter#87]
Most exporters are being distributed within a gzipped tarball, distributing this exporter in the same way will ease and make a bit more consistent deployment scripts. Other than that, thanks a lot for the great work with this exporter 👍

**Comment by c4milo** [comment]
You could use https://github.com/c4milo/github-release for this. (shameless self plug). But, honestly, the initial request was legit since I'm currently instrumenting some services and your exporter popped up in my search.

**Comment by c4milo** [comment]
I did fork this repo and added a new makefile https://github.com/c4milo/postgres_exporter 

If you are interested in the changes, I'll be more than happy to send you a PR and remove my fork.

**Comment by sathieu** [comment]
@c4milo Please send a PR.

@wrouesnel Please consider this feature request.

Thank you both!

**Comment by wrouesnel** [comment]
Fixed for a while now. We also have zip releases for windows!
