### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Musashisan** [wrouesnel/postgres_exporter#88]
After launching the Make
`make -C tools
make[1]: Entering directory '/opt/postgres_exporter/postgres_exporter-0.2.1/tools'
make[1]: Nothing to be done for 'DEFAULT'.
make[1]: Leaving directory '/opt/postgres_exporter/postgres_exporter-0.2.1/tools'
gometalinter --disable-all --enable=gofmt --vendor
Using 2 processes
gometalinter -j 2 --deadline=30s --disable=gotype --disable=gocyclo
pg_setting.go:11:2:warning: could not import github.com/prometheus/client_golang/prometheus (cannot find package "github.com/prometheus/client_golang/prometheus" in any of: (staticcheck)
pg_setting.go:12:2:warning: could not import github.com/prometheus/common/log (cannot find package "github.com/prometheus/common/log" in any of: (staticcheck)
postgres_exporter.go:19:2:warning: could not import gopkg.in/yaml.v2 (cannot find package "gopkg.in/yaml.v2" in
any of: (staticcheck)
postgres_exporter.go:21:2:warning: could not import github.com/blang/semver (cannot find package "github.com/blang/semver" in any of: (staticcheck)
postgres_exporter.go:22:4:warning: could not import github.com/lib/pq (cannot find package "github.com/lib/pq" in any of: (staticcheck)
postgres_exporter.go:23:2:warning: could not import github.com/prometheus/client_golang/prometheus (cannot find
package "github.com/prometheus/client_golang/prometheus" in any of: (staticcheck)
postgres_exporter.go:24:2:warning: could not import github.com/prometheus/common/log (cannot find package "github.com/prometheus/common/log" in any of: (staticcheck)
pg_setting.go:16:30:warning: undeclared name: prometheus (staticcheck)
pg_setting.go:50:30:warning: undeclared name: prometheus (staticcheck)
postgres_exporter.go:107:30:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:111:42:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:125:20:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:144:13:warning: undeclared name: prometheus (staticcheck)
postgres_exporter.go:145:14:warning: undeclared name: prometheus (staticcheck)
postgres_exporter.go:218:76:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:219:76:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:235:106:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:246:85:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:251:55:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:262:15:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:271:4:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:295:4:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:304:4:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:316:4:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:349:37:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:380:47:warning: undeclared name: semver (staticcheck)
postgres_exporter.go:477:28:warning: undeclared name: semver (staticcheck)
...`

So i tryed to just make postgres_exporter:
`fatal: Not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
postgres_exporter.go:21:2: cannot find package "github.com/blang/semver" in any of:
        /usr/lib/go-1.6/src/github.com/blang/semver (from $GOROOT)
        /opt/postgres_exporter/postgres_exporter-0.2.1/src/github.com/blang/semver (from $GOPATH)
postgres_exporter.go:22:2: cannot find package "github.com/lib/pq" in any of:
        /usr/lib/go-1.6/src/github.com/lib/pq (from $GOROOT)
        /opt/postgres_exporter/postgres_exporter-0.2.1/src/github.com/lib/pq (from $GOPATH)
pg_setting.go:11:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/lib/go-1.6/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /opt/postgres_exporter/postgres_exporter-0.2.1/src/github.com/prometheus/client_golang/prometheus (from
$GOPATH)
pg_setting.go:12:2: cannot find package "github.com/prometheus/common/log" in any of:
        /usr/lib/go-1.6/src/github.com/prometheus/common/log (from $GOROOT)
        /opt/postgres_exporter/postgres_exporter-0.2.1/src/github.com/prometheus/common/log (from $GOPATH)
postgres_exporter.go:19:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/lib/go-1.6/src/gopkg.in/yaml.v2 (from $GOROOT)
        /opt/postgres_exporter/postgres_exporter-0.2.1/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [postgres_exporter] Error 1`

Manual solution:
`export GOPATH=`pwd`
go get github.com/blang/semver
go get github.com/lib/pq
go get github.com/prometheus/common/log
go get github.com/prometheus/client_golang/prometheus
go get gopkg.in/yaml.v2
go get gopkg.in/check.v1
make postgres_exporter`

System information:

Downloaded tar file: v0.2.1.tar.gz

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

apt-get install golang

**Comment by wrouesnel** [comment]
Hmm somethings gone very wrong there. We're definitely not missing that many dependencies.

**Comment by wrouesnel** [comment]
Just checked the build now, and it's working fine. Please try building from the normal `GOPATH` using a repo checked out via `go get github.com/wrouesnel/postgres_exporter`.
