### ISSUE TITLE
custom queries file 

### ISSUE THREAD

**Issue by ratheesh001** [wrouesnel/postgres_exporter#90]
Hi, 
I am using the following docker command to start the exporter 
`docker run -e DATA_SOURCE_NAME="postgresql://postgres:postgres@xxxxxx:5432/mydb?sslmode=disable"  -p 9187:9187 wrouesnel/postgres_exporter`

Its getting started and am able to see the default metrics in the URL.

How can i use custom config file for queries? i tried passing ` -extend.query-path=/home/prometheus/queries.yaml ` in the docker run command. But seems to be not working.

Thanks
Ratheesh

**Comment by wrouesnel** [comment]
You need to bind mount the file into the docker container.

**Comment by ratheesh001** [comment]
Thanks wrouesnel for you reply. 
I tried mounting like below, but i could not able to see the custom metrics from queries
 docker run -v /home/prometheus/queries.yaml:/home/prometheus/queries.yaml -e  DATA_SOURCE_NAME="postgresql://postgres:postgres@lon1ppf03.int.openbet.com:5432/openbet?sslmode=disable"  -e extend.query-path=/home/prometheus/queries.yaml -p 9187:9187 wrouesnel/postgres_exporter

am new to docker, so not able to figure out how to give the path in docker run command.

Thanks,
Ratheesh

**Comment by wrouesnel** [comment]
That looks correct. What logs are you getting from running it like this?

**Comment by ratheesh001** [comment]
am not sure where i can find the log file. I could see only the below printed after the container start 

time="2017-07-27T08:36:12Z" level=info msg="Semantic Version Changed: 0.0.0 -> 9.5.7" source="postgres_exporter.go:901" 
time="2017-07-27T08:36:12Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1013"

**Comment by ratheesh001** [comment]
In docker inspect i could see the log path as /var/lib/docker/containers/07c763da9e0f8236fcefcda6ee17ed3fd2c25bb4e4146d20fa9bc6582319ce23/07c763da9e0f8236fcefcda6ee17ed3fd2c25bb4e4146d20fa9bc6582319ce23-json.log

I could see the above lines only in that file

**Comment by ratheesh001** [comment]
Its working fine with the below command.

`docker run -v /home/prometheus/queries.yaml:/home/prometheus/queries.yaml -e DATA_SOURCE_NAME="postgresql://postgres:postgres@lon1ppf03.int.openbet.com:5432/openbet?sslmode=disable" -p 9187:9187 wrouesnel/postgres_exporter  **-extend.query-path=/home/prometheus/queries.yaml**`

Thanks wrouesnel for your time.
