### ISSUE TITLE
Postgres 10 beta support

### ISSUE THREAD

**Issue by piotrkochan** [wrouesnel/postgres_exporter#91]
It'll be nice to release version which supports Postgres 10 beta

```
 PostgreSQL 10beta1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204, 64-bit\n" source="postgres_exporter.go:966" 
```

**Comment by wrouesnel** [comment]
Is there a published Docker container on docker hub for it yet (they're the main way the exporter gets tested).

**Comment by piotrkochan** [comment]
There are 2 Postgres 10beta releases in the DockerHub

```
10-beta2, 10 (10/Dockerfile)
10-beta2-alpine, 10-alpine (10/alpine/Dockerfile)
```

https://hub.docker.com/_/postgres/
