### ISSUE TITLE
Container in docker swarm throws panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by endeepak** [wrouesnel/postgres_exporter#93]
This error is thrown when I run the postgres_exporter container as a service inside docker swarm

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6fbe6a]

goroutine 18 [running]:
main.(*Exporter).scrape(0xc4201080c0, 0xc42010c1e0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:956 +0x25a
main.(*Exporter).Collect(0xc4201080c0, 0xc42010c1e0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:744 +0x39
main.(*Exporter).Describe(0xc4201080c0, 0xc42010c180)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/postgres_exporter.go:737 +0xb0
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x9459c0, 0xc4201080c0, 0xc42010c180)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:220 +0xbc
```

**Observations**
* It works well when I run the container as standalone container in same server
* The `DATA_SOURCE_NAME` is set properly. I've verified this by getting inside container (I had to create docker [image](https://hub.docker.com/r/sunbird/postgres_exporter/) with alpine linux for debugging this)
```
/ # env
DATA_SOURCE_NAME="postgresql://postgres_exporter:maskedpassword@10.1.0.4:5432/postgres"
```
* I've verified that psql client can connect to postgres using same connection string

```
apk --update add postgresql-client
/ # psql "postgresql://postgres_exporter:maskedpassword@10.1.0.4:5432/postgres"
psql (9.6.3, server 9.5.7)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
postgres=#
```
* `Dockerfile` used for creating image for debugging

```
FROM alpine:3.6

ARG POSTGRES_EXPORTER_VERSION=v0.2.1

RUN apk --no-cache add openssl

RUN wget -O /usr/local/bin/postgres_exporter https://github.com/wrouesnel/postgres_exporter/releases/download/$POSTGRES_EXPORTER_VERSION/postgres_exporter && \
    chmod +x /usr/local/bin/postgres_exporter

EXPOSE 9187

ENTRYPOINT ["/usr/local/bin/postgres_exporter"]
```

**Comment by endeepak** [comment]
Should the condition be `pErr == nil` instead of `pErr != nil` in https://github.com/wrouesnel/postgres_exporter/blob/v0.2.1/postgres_exporter.go#L955?

**Comment by wrouesnel** [comment]
Hm looks like a definite logic bug. I'll get that fixed.

**Comment by endeepak** [comment]
Thanks @wrouesnel. It would be good to have a release with that fix. It will help debugging container failures

**Comment by wrouesnel** [comment]
I'll get one released later tonight. Thanks for the report!

**Comment by wrouesnel** [comment]
Okay I don't know how you've been tripping it, but bizarrely this code has actually been broken all along and the bug you identified stops it from crashing normally. The URL parse library almost always succeeds even with broken URLs, so we just never entered that section.

Interestingly I can't find a test case where the url.Parse() function actually fails running locally so I'm not sure why it's crashing for you.

**Comment by endeepak** [comment]
I'm also not sure about the url parse error. I'm hoping that fixing the logic mentioned above would log the real error why DB connection is failing. Logging the url.Parse error would also be useful to understand why it fails

**Comment by endeepak** [comment]
I was trying to fix that logic alone and build a binary which can be used in container for debugging my issue. I tried building the binary on mac osx, couldn't get it working

Running `make` gets stuck with these errors ->
```
➜  postgres_exporter git:(master) make
/Library/Developer/CommandLineTools/usr/bin/make -C tools
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
make[1]: Nothing to be done for `DEFAULT'.
gometalinter --disable-all --enable=gofmt --vendor
cat: /proc/cpuinfo: No such file or directory
cat: /proc/cpuinfo: No such file or directory
Using 0 processes
gometalinter -j        0 --deadline=30s --disable=gotype --disable=gocyclo
```

**Comment by wrouesnel** [comment]
Unfortunately I don't develop of OS X so my makefiles tend not to be compatible across platforms. I have a PR up containing the fixes, I'll cut it to a release ASAP - #94.

**Comment by endeepak** [comment]
Thanks for the release @wrouesnel. Getting the error logged now

```
monitor_postgres_exporter.1.bbsq2w5nqohe@swarmm-agentpublic-18950373000008    | time="2017-08-04T03:20:02Z" level=info msg="Error opening connection to database (could not parse DATA_SOURCE_NAME): missing \"=\" after \"\\\"postgresql://postgres_exporter:xxxxxxx@10.1.0.4:5432/postgres\\\"\" in connection info string\"" source="postgres_exporter.go:977"
```

**Comment by endeepak** [comment]
The above error went away after adding `?sslmode=disable` in connection string. I'm getting a new error now

```
monitor_postgres_exporter.1.g8atsb6uzvyw@swarmm-agentpublic-18950373000009    | time="2017-08-04T04:13:08Z" level=info msg="Error opening connection to database (could not parse DATA_SOURCE_NAME): pq: Could not detect default username. Please provide one explicitly." source="postgres_exporter.go:977"
```

**Comment by endeepak** [comment]
It was issue with quotes around connection string in docker compose file. Found the answer here https://stackoverflow.com/a/37764191/69362. I had to change it to

```
environment:
    - DATA_SOURCE_NAME=postgresql://postgres_exporter:xxxxxxx@10.1.0.4:5432/postgres?sslmode=disable
```

earlier it was

```
environment:
    - DATA_SOURCE_NAME="postgresql://postgres_exporter:xxxxxxx@10.1.0.4:5432/postgres?sslmode=disable"
```

Thanks @wrouesnel for your timely help. It would be good to add this in README file for others trying to use this in compose file / docker swarm. Please let me know if you need help
