### ISSUE TITLE
NaN value for pg_stat_replication_pg_xlog_location_diff

### ISSUE THREAD

**Issue by tonymadbrain** [wrouesnel/postgres_exporter#97]
No data for pg_stat_replication_* except pg_stat_replication_pg_xlog_location_diff - NaN
Postgres 9.6, replication is working.

**Comment by wrouesnel** [comment]
@tonymadbrain Are you running the exporter as a superuser (postgres)? Could you post the result (redacted as you see fit) of `select * pg_stat_replication` ?

**Comment by briffle** [comment]
I am having the same issue.  Both for pg_stat_replication_pg_xlog_location_diff and pg_replication_lag.

I have run the commands in the readme for setting up a dedicated user:

```
CREATE USER postgres_exporter PASSWORD 'password';
ALTER USER postgres_exporter SET SEARCH_PATH TO postgres_exporter,pg_catalog;

-- If deploying as non-superuser (for example in AWS RDS)
-- GRANT postgres_exporter TO :MASTER_USER;
CREATE SCHEMA postgres_exporter AUTHORIZATION postgres_exporter;

CREATE VIEW postgres_exporter.pg_stat_activity
AS
  SELECT * from pg_catalog.pg_stat_activity;
  
GRANT SELECT ON postgres_exporter.pg_stat_activity TO postgres_exporter;

CREATE VIEW postgres_exporter.pg_stat_replication AS
  SELECT * from pg_catalog.pg_stat_replication;

GRANT SELECT ON postgres_exporter.pg_stat_replication TO postgres_exporter;
```
However, when running ``` select * from pg_stat_replication ``` I only get PID, USESYSID, USENAME, and APPLICATION_NAME columns with data, so I think this is a permission error.

To create this user, I did log in as they postgres user, and connect directly to the db as that superuser.
I left this part commented out, since I was connecting and running the commands as the superuser, but maybe I misunderstood?
```
-- If deploying as non-superuser (for example in AWS RDS)
-- GRANT postgres_exporter TO :MASTER_USER;
```

**Comment by briffle** [comment]
Not sure if this is helpful or not, but saw in [pganalyze/collector](https://github.com/pganalyze/collector) , they use a function with a security definition. I tried running this as super user: 
```
CREATE OR REPLACE FUNCTION postgres_exporter.get_stat_replication_test() RETURNS SETOF pg_stat_replication AS $$
 /* postgres_exporter */ SELECT * FROM pg_catalog.pg_stat_replication;
$$ LANGUAGE sql VOLATILE SECURITY DEFINER;
CREATE FUNCTION
```
And then running as the postgres_exporter user:
```select * from from postgres_exporter.get_stat_replication_test();``` 
returned all the columns.

**Comment by wrouesnel** [comment]
Flagging this as documentation and closing it since it seems like we have a resolution? If anyone wants to contribute a definitive bit of documentation on where this is needed that would be great.

**Comment by jamesbot9000** [comment]
Hi,

What exactly is the resolution here? I would like to use this as the non super user. This thread just says it works if you create a SQL function, but that does not make postgres exporter work. Can someone explain how to prevent the NaN? the instructions say to set up a view but it seems the postgres exporter code does not actually use that view, but queries pg_stat_replication directly. Seems to me this is an actual bug and not a documentation issue. Can you please explain what the resolution is?

thank you

**Comment by jamesbot9000** [comment]
If I do this: 
postgres_exporter.get_stat_replication_test() as noted above, I get the full replication information. If I do this
select * from postgres_exporter.pg_stat_replication;

I get only the first three fields. So it seems the instructions are missing something? Sorry if I sound confused, I don't have a lot of experience with psql permissions

**Comment by snarlistic** [comment]
@jamesbot9000 Please see https://github.com/wrouesnel/postgres_exporter/pull/253. I'm pretty sure this will help you understand what the exact resolution here is. It took me quiet some time and learning to figure it out myself. So hopefully this wil help others too.
