### ISSUE TITLE
custom query parsing error : 

### ISSUE THREAD

**Issue by matth-c3** [wrouesnel/postgres_exporter#99]
Hello,

I'm trying to add custom metric to get the list of queries currently executed and there execution duration using -extend.query-path and yaml file.

Here is the detail of my yaml file:

> pg_query_statement:

>  query: "select pid, datname, now()-pg_stat_activity.query_start AS duration, query, state, waiting FROM pg_stat_activity WHERE datname not in ('rdsadmin') order by duration desc"
  metrics:
    - pid:
        usage: "LABEL"
        description: "Pid of the query"
    - datname:
        usage: "GAUGE"
        description: "Name of the table"
    - duration:
        usage: "COUNTER"
        description: "duration in seconds"
    - query:
        usage: "COUNTER"
        description: "Query executed"
    - state:
        usage: "GAUGE"
        description: "State of the query"
    - waiting:
        usage: "GAUGE"
        description: "Waiting time"

When executed I get the following error : 

>INFO[0000] Unexpected error parsing column:  pg_query_statement query [82 79 76 76 66 65 67 75]
  source=postgres_exporter.go:877
INFO[0000] Unexpected error parsing column:  pg_query_statement state [105 100 108 101]
  source=postgres_exporter.go:877
INFO[0000] Unexpected error parsing column:  pg_query_statement waiting false
  source=postgres_exporter.go:877
INFO[0000] Unexpected error parsing column:  pg_query_statement datname [99 51 101 110 103 105 101 103 114 105 100 111 112 115]

Thank you by advance.

**Comment by wrouesnel** [comment]
You can't parse text columns as metrics. You need to specify them as either LABEL or DISCARD types.

**Comment by matth-c3** [comment]
Ok thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
